uktrade/icms

web/domains/case/access/flows.py
web/domains/case/access/forms.py
web/static/web/js/request-access.js
web/templates/web/request-access.html

Next step is wiring the viewflow with the page.
Once Exporter access is done, the showing/hiding of the fields will probably need to be revisited to get the other types working.

Request access page - show/hide form fields

---

.dockerignore
.gitignore
web/static/web/css/fox.css
web/templates/web/case-fir-sidebar.html
web/templates/web/review-access-request.html

First step of FIR integration is to have a sidebar on access cases screen
I guess the question here is if the way I'm doing the "access request" url works with viewflow or will break it.
If it does break viewflow I suggest a simpler JS way of forcing the POST request that will automatically attach to the a tag (with a specific data tag or css class) and create a form and post it for us

FIR sidebar

---

web/domains/case/access/views.py
web/domains/case/forms.py
web/static/web/css/fox.css
web/templates/forms/fields.html
web/templates/web/access-request/partials/fir-item.html

style read only forms to look like normal text
click on a form edit button triggers a post action and shows the edit form in place

styling display forms + show edit form in pace + use post actions

---

web/domains/case/access/views.py
web/domains/case/forms.py
web/domains/case/models.py
web/templates/web/access-request/access-request-fir-list.html
web/templates/web/access-request/partials/back-to-workbasket.html
web/templates/web/access-request/partials/fields/fir-status.html
web/templates/web/access-request/partials/fields/form-buttons-row.html
web/templates/web/access-request/partials/fir-action-button.html
web/templates/web/access-request/partials/fir-item.html

* add new FIR
* edit existing FIR

Add and Edit FIR

---

web/domains/case/forms.py
web/static/web/css/fox.css
web/templates/forms/fields.html

adds help text to CC emails field on FIR form

help text on FIR form

---

web/static/web/css/fox.css
web/static/web/js/file-upload.js
web/templates/base.html
web/templates/web/access-request/access-request-fir-list.html
web/templates/web/access-request/partials/fields/file-upload-button.html
web/templates/web/access-request/partials/fir-item-file-upload-row.html
web/templates/web/access-request/partials/fir-item-file-upload.html
web/templates/web/access-request/partials/fir-item.html

FIR FIle upload layout for edit and display forms
Display form:
edit form:

File upload layout

---

Makefile
config/settings/production.py
scripts/entry.sh

Change javascript compression to happen offline rather than in request/
response loop.

Fix javascript file not found with whitenoise.

---

Pipfile
Pipfile.lock
config/settings/base.py
config/settings/development.py
web/domains/case/access/views.py
web/domains/file/models.py
web/static/web/css/fox.css
web/templates/web/access-request/partials/fir-item-file-upload-row.html
web/templates/web/access-request/partials/fir-item-file-upload.html
web/utils/s3upload.py
web/utils/utils.py

* new layout to display errors
* s3: move file to correct location after passing validations
* s3: delete uploaded file on error

file upload

---

web/domains/case/access/views.py
web/domains/case/models.py
web/static/web/css/fox.css
web/static/web/js/file-actions.js
web/templates/web/access-request/partials/fir-item-file-upload-row.html
web/templates/web/access-request/partials/fir-item-file-upload.html
web/utils/s3upload.py

restore deleted file

---

web/domains/case/access/views.py
web/static/web/js/file-actions.js
web/templates/web/access-request/partials/fir-item-file-upload.html

file upload actions are done as part of the save action, to ensure any changes to form are saved if a file action is performed
click the save button redirects to list view, performing file actions keeps user in edit view

return to edit mode on file upload actions

---

web/domains/template/forms.py
web/domains/template/models.py
web/domains/template/urls.py
web/domains/template/views.py

added:
* new template types
* display template view
very basic view, no styling as of yet

search templates

---

Dockerfile
Makefile
Pipfile
Pipfile.lock
config/settings/test.py
docker-compose.yml
features/environment.py
features/login.feature
features/steps/login.py
features/steps/shared.py
web/domains/country/models.py
web/domains/firearms/models.py
web/domains/legislation/models.py
web/tests/domains/firearms/test_models.py

Initial Selenium + behave setup
Setting up different test db and circle ci config to be done in a different story

SELENIUM SETUP

---

Makefile
features/environment.py
features/importer/importers-display.feature
features/importer/search.feature
features/steps/importer/steps.py
features/steps/shared.py
test_reports/TESTS-access-request.request-access-as-agent-of-exporter.xml
test_reports/TESTS-access-request.request-access-as-agent-of-importer.xml
test_reports/TESTS-access-request.request-access-as-exporter.xml
test_reports/TESTS-access-request.request-access-as-importer.xml
test_reports/TESTS-auth.login.xml
test_reports/TESTS-auth.logout.xml
web/domains/importer/views.py
web/templates/forms/fields.html
web/templates/partial/offices-display.html
web/templates/partial/offices/office-list-body-display.html
web/templates/partial/offices/office-list-display.html
web/templates/partial/offices/office-list-header-display.html
web/templates/partial/single-field-view-mode.html
web/templates/partial/view-form-fields.html
web/templates/tables/tables.html
web/templates/web/domains/importer/view.html

* view import action on importer list page
* display importer page
* show current importer offices
* show archived importer offices

show importer offices

---

features/importer/importers-edit.feature
features/steps/importer.py
web/domains/importer/forms.py
web/domains/importer/models.py
web/domains/importer/urls.py
web/domains/importer/views.py
web/domains/user/models.py
web/templates/web/domains/importer/view.html

- Show different fields for individuals/organizations.
- Implement agent-specific view of importer.
- Show an info box saying they're an agent of XXX (with a link).
- Don't show agents section (agents can't have agents).

ICMSLST-402 Improve detail view of importer.

---

Dockerfile
config/gunicorn.py
requirements-base.txt
scripts/entry.sh

Eventlet allows to use the same thread for concurrent requests
- remover worker (use one worker)
- set worker_class to eventlet
- set worker_connections to 1000

ICMSLST-414 Use eventlet with gunicorn

---

web/domains/importer/urls.py
web/domains/importer/views.py
web/templates/forms/fields.html
web/templates/partial/offices-edit.html
web/templates/web/domains/importer/company_list.html
web/templates/web/domains/importer/create.html
web/templates/web/domains/importer/edit.html
web/templates/web/domains/importer/search-companies.html
web/tests/domains/importer/test_views.py

Add offices (m2m) to importer and allow to choose company from companies house.

Feature/icmslst 316 create importer - add offices and companies

---

Dockerfile
config/gunicorn.py
requirements-base.txt
scripts/entry.sh

Gevent allows to use the same thread for concurrent requests
set worker_class to gevent
set worker_connections to 1000
monkey patch psycopg2

ICMSLST-414 Add gevent and psycogreen to gunicorn

---

Makefile
config/settings/base.py
requirements-base.txt
requirements-dev.txt
web/admin.py
web/domains/case/export/forms.py
web/domains/case/export/views.py
web/domains/exporter/models.py
web/domains/user/models.py
web/menu/menu.py
web/models/__init__.py
web/permissions.py
web/tests/domains/case/export/test_views.py

In more detail:
* Add web/permissions.py for global permissions.
* Add django-guardian for object-level permissions.
* Add `make pip-check` to check dependencies for possible updates.
* Add `make psql` to easily browse the database locally.

ICMSLST-424 Add new permission scheme, use it for export applications.

---

web/domains/case/export/forms.py
web/domains/exporter/models.py

It's now using django-guardian.

ICMSLST-443 Implement exporter filtering for export application screen.

---

web/domains/case/access/forms.py
web/domains/case/access/urls.py
web/domains/case/access/views.py
web/notify/notify.py
web/notify/utils.py
web/static/web/js/pages/request-access.js
web/static/web/js/pages/review-request-access.js
web/templates/web/domains/case/access/partials/access-request-list.html
web/templates/web/domains/case/access/partials/pending-requests.html
web/templates/web/domains/case/access/request-access-success.html
web/templates/web/domains/case/access/request-exporter-access.html
web/templates/web/domains/case/access/request-importer-access.html
web/templates/web/menu/menu.html
web/tests/domains/case/access/test_views.py

Only allow to create an access request not to manage it.

ICMS-440 Convert viewflow views to create an Access Request

---

web/domains/case/export/views.py

Check user has access to exporter when creating a new Export Application

ICMSLST-450 Check user has access to exporter

---

web/domains/case/access/approval/forms.py
web/domains/case/access/approval/views.py
web/domains/workbasket/views.py
web/templates/web/domains/case/access/case-approval-respond.html
web/templates/web/domains/case/access/case-user-base.html
web/templates/web/domains/workbasket/partials/approval-request.html
web/templates/web/domains/workbasket/partials/workbasket-item-user.html

Importer's/Exporter's contacts can approve/reject approval request (people asking to be a contact on importer/exporter).

ICMSLST-461 Approve/Reject Approval Request for user

---

web/domains/firearms/forms.py
web/domains/firearms/urls.py
web/domains/firearms/views.py
web/menu/menu.py
web/static/web/css/fox.css
web/static/web/js/main.js
web/templates/partial/firearms/sidebar.html
web/templates/web/domains/firearms/create.html
web/templates/web/domains/firearms/edit.html
web/templates/web/domains/firearms/group/create.html
web/templates/web/domains/firearms/group/edit.html
web/templates/web/domains/firearms/group/list.html
web/templates/web/domains/firearms/group/view.html

Displaying calibres on search was done in https://github.com/uktrade/icms/compare/feature/ICMSLST-229-matching-calibres?expand=1#diff-dcda07609ab3ecf245c98b45de8b61d7fadf97c3b6825ea7b5457a7ece7ebc81R40-R46

ICMSLST-229 Display matching calibres on search

---

web/domains/commodity/forms.py
web/static/web/css/fox.css
web/static/web/js/pages/create-commodity-group.js
web/templates/web/domains/commodity/group/create.html
web/tests/domains/commodity/factory.py
web/tests/domains/commodity/test_forms.py

Allow to add unit when Commodity Group type is `CATEGORY`

ICMSLST-464 Add unit to CommodityGroup

---

Makefile
web/management/commands/create_exporter.py
web/management/commands/create_importer.py

Usage:
```bash
$ make manage COMMAND="create_importer"
$ make manage COMMAND="create_exporter"
$ make manage COMMAND="create_exporter --first_name=John --last_name=McCarthy"
```

ICMSLST-466 Management commands to create importer/exporter

---

web/domains/importer/forms.py
web/domains/importer/models.py
web/domains/importer/views.py
web/management/commands/create_importer.py
web/templates/web/domains/importer/view.html

* remove forms to display information and use instance instead
* add EORIs and registered numbers for display

ICMSLST-280 Add attributes to importer display view

---

web/domains/template/forms.py
web/models/mixins.py

For CFS schedules and declarations.

ICMSLST-483 Disallow multiple translations for the same country.

---

web/domains/user/models.py
web/templates/web/menu/menu.html

Use `full_name` property from `User` model

ICMSLST-495 Fix title showing `None` in menu bar

---

Dockerfile
README.md
config/settings/development.py
requirements-base.txt
requirements-dev.txt

Added graphviz libraries to draw db schema
Changed docker image to use 'slim' for better compatibility
Optimised the docker build process to take advantage of caching

Added django extensions package

---

web/domains/case/_import/forms.py
web/domains/case/_import/models.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/static/web/js/pages/withdrawals.js
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/management.html
web/templates/web/domains/case/import/management/checklist.html
web/templates/web/domains/case/import/management/withdrawals.html
web/templates/web/domains/workbasket/partials/workbasket-item.html

Allow ILB Admin to review case withdrawals made by importer and to accept or reject it with a response.

ICMSLST-507 Accept/Reject withdrawals from ILB Admin

---

web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/export/urls.py
web/domains/case/export/views.py
web/domains/case/views.py
web/templates/partial/case/case-note-box.html
web/templates/partial/case/export/sidebar.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/edit-note.html
web/templates/web/domains/case/export/management-base.html
web/templates/web/domains/case/list-notes.html

Refactor and re-use views from ExportApplication to manage notes

ICMSLST-510 Add case note to import application

---

Makefile
README.md
web/management/commands/add_dummy_data.py

This will make it trivial for developers to start from a clean DB in a
few seconds.

ICMSLST-541 Add add_dummy_data management command.

---

web/domains/case/_import/forms.py
web/domains/case/_import/models.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/migrations/0001_initial.py
web/static/web/js/pages/approval-response.js
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/partials/firearms/oil-documents.html
web/templates/web/domains/case/import/partials/firearms/oil-goods.html
web/templates/web/domains/case/import/prepare-response.html

Allow ILB Admin to record acceptance/rejection of the application

ICMSLST-511 Add main form for response preparation

---

web/domains/case/_import/firearms/views.py
web/domains/case/_import/forms.py
web/domains/case/_import/models.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/migrations/0001_initial.py
web/templates/web/domains/case/import/edit-cover-letter.html
web/templates/web/domains/case/import/partials/firearms/oil-documents.html

Note as of today template migration for cover letter has not been
extracted correctly from the database.

ICMSLST-511 Edit Cover Letter

---

web/domains/case/_import/views.py
web/tests/domains/case/_import/firearms/test_views.py

Code to render the template was indented and never returned a response
when form was invalid.

ICMSLST-588 Fix create application not returning http response

---

web/domains/case/_import/firearms/forms.py
web/domains/case/_import/firearms/views.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/authorisation.html
web/templates/web/domains/workbasket/partials/workbasket-item.html

Application authorisation set the state of the application to 'PROCESSING' and allow ILB to sign documents (TODO).

ICMSLST-512 Add application authorisation

---

web/domains/case/_import/views.py
web/domains/case/export/views.py
web/domains/case/views.py
web/templates/flow/task-manage-export.html
web/templates/web/domains/case/manage/edit-note.html
web/templates/web/domains/case/manage/list-notes.html

And update notes' views as notes are shared between import and export applications.

ICMSLST-489 Move template for case note

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/firearms/forms.py
web/domains/case/_import/firearms/models.py
web/domains/case/_import/firearms/urls.py
web/domains/case/_import/firearms/views.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/views.py
web/domains/case/_import/wood/views.py
web/migrations/0016_userimportcertificate.py
web/templates/forms/widgets/firearms/checkbox_select_table.html
web/templates/partial/certificates/list.html
web/templates/web/domains/case/import/firearms/certificates/edit.html

Changes:
- Can download certifcate file
- Each certificate can only have one file
- Updated UI to match wood certificates
- Added delete certificate view
- Updated constabulary email templates to work with changed model.

ICMSLST-620 Update firearms user cerificates to match wood certificates.

---

web/domains/case/_import/firearms/forms.py
web/domains/case/_import/firearms/models.py
web/domains/case/_import/firearms/views.py
web/migrations/0015_alter_oil_application.py

Also changed the default label for unknown to match other selects inputs.

ICMSLST-623 Change type of know_bought_from to BooleanField.

---

web/domains/case/_import/views.py
web/templates/web/domains/case/import/view_derogations.html
web/templates/web/domains/workbasket/partials/workbasket-item.html

__Merging to a feature branch__
Add the ability to take/release ownership of a 'Derogation' application and to view the application.

ICMSLST-486 Add manage and view derogations for ILB Admin

---

web/domains/case/_import/wood/urls.py
web/domains/importer/urls.py
web/domains/importer/views.py
web/domains/section5/forms.py
web/templates/partial/section5-authorities.html
web/templates/partial/section5-authorities/list.html
web/templates/web/domains/importer/add-document-section5-authority.html
web/templates/web/domains/importer/detail-section5-authority.html
web/templates/web/domains/importer/edit-section5-authority.html
web/tests/domains/case/_import/test_views.py
web/tests/domains/importer/test_views.py

Also add viewing uploaded documents to importer/section5.
Also do cleanups in that area:
* Remove unnecessary importer_pk from various URLs.
* Shorten URLs / view names / function names by removing "[-_]_authorities".

ICMSLST-635 Use single-file uploads for importer/section5.

---

web/domains/case/_import/views.py
web/templates/web/domains/case/import/partials/wood/contract_documents_list.html
web/templates/web/domains/case/import/partials/wood/supporting_documents_list.html
web/templates/web/domains/case/import/view_case.html
web/templates/web/domains/case/import/wood/edit.html
web/templates/web/domains/case/import/wood/view.html
web/tests/domains/case/_import/firearms/test_views.py

Other changes:
- Refactor edit wood application to use same partial templates.
- Take ownership link now redirects to view application view.

ICMSLST-640 Add view wood application view.

---

web/domains/case/_import/wood/forms.py
web/templates/web/domains/case/import/manage/case.html

Also updated wood quota checkbox form to correctly use verbose_name model values.

ICMSLST-644 Display SIGL link for Wood Quota applications.

---

web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/views.py
web/static/web/css/fox.css
web/templates/partial/case/import/fa-sil/sidebar.html
web/templates/web/domains/case/import/fa-sil/edit.html

Edit application for importer.

ICMSLST-656 Edit Firearms and Ammunition - Specific Import Licence (SIL)

---

web/converters.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/export/urls.py
web/domains/case/export/views.py
web/domains/case/urls.py
web/domains/case/views.py
web/templates/partial/case/case-note-box.html
web/templates/partial/case/export/sidebar.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/manage/add-note-document.html
web/templates/web/domains/case/manage/edit-note.html
web/templates/web/domains/case/manage/list-notes.html
web/urls.py

This adds the framework of being able to have just one URL/view for shared
code in case management for all of import/export/accessrequest, and also
uses it to move all note functions over.

ICMSLST-659 Refactor case management code (notes).

---

web/templates/partial/case/case-fir-box.html

Feature doesn't exist in ICMS1 and doesn't work

ICMSLST-674 Remove close FIR

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/views.py
web/domains/case/_import/wood/views.py
web/templates/web/domains/workbasket/partials/workbasket-item-user.html
web/templates/web/domains/workbasket/partials/workbasket-item.html
web/tests/domains/workbasket/test_views.py

Also:
-  Fix edit_licence not showing existing model data.
-  Add separation between workbasket action links.

ICMSLST-673 Add missing case_type to a few views.

---

setup.cfg
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/access/urls.py
web/domains/case/access/views.py
web/domains/case/urls.py
web/domains/case/views.py
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/access/case-user-base.html
web/templates/web/domains/case/access/list-exporter.html
web/templates/web/domains/case/access/list-importer.html
web/templates/web/domains/case/import/view_derogations.html
web/templates/web/domains/case/import/wood/view.html
web/templates/web/domains/case/list-firs.html
web/templates/web/domains/case/respond-fir.html
web/templates/web/domains/workbasket/partials/workbasket-item-user.html
web/templates/web/domains/workbasket/partials/workbasket-item.html

This is for all of import/export/accessrequests.
Also fix a few random bugs in "view case":
* "View supporting document" in derogations view case was broken.
* Applicant actions in workbasket for derogations were missing.
* "Commodity code" misspelled in wood quota.

ICMSLST-673 Refactor case management code (view case).

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/_import/wood/views.py
web/domains/case/urls.py
web/templates/partial/case/export/sidebar-management.html
web/templates/web/domains/case/import/manage/prepare-response.html

Endorsements are only used for import applications, so it doesn't make
sense to move them up to case/views level.

ICMSLST-668 Clean up import/endorsements code.

---

web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/urls.py
web/domains/case/views.py
web/templates/partial/case/export/sidebar-management.html
web/templates/partial/case/import/sidebar-management.html
web/templates/partial/update-requests/box.html
web/templates/web/domains/case/update-requests.html

- Remove non ILB Admin views for Update Requests (To be implemented in ICMLST-679)
- Add missing template to create Update Request
- Fix closing request
- Move update requests urls from import to case
- Make update request available to export case management (ICMSLST-432)

ICMSLST-648 Fix update request for ILB Admin

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/forms.py
web/domains/case/_import/models.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/_import/wood/views.py
web/domains/case/export/models.py
web/domains/case/forms.py
web/domains/case/models.py
web/domains/case/urls.py
web/domains/case/views.py
web/migrations/0001_initial.py
web/templates/partial/case/export/sidebar-management.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/manage/add-endorsement.html
web/templates/web/domains/case/import/manage/edit-cover-letter.html
web/templates/web/domains/case/import/manage/edit-endorsement.html
web/templates/web/domains/case/import/manage/edit-goods-licence.html
web/templates/web/domains/case/import/manage/edit-licence.html

This also introduces ApplicationBase, a common baseclass for
Import/ExportApplication.

ICMSLST-683 Refactor case management code (prepare response).

---

web/domains/case/_import/views.py
web/domains/case/fir/forms.py
web/domains/case/urls.py
web/domains/case/views.py
web/static/web/css/fox.css
web/static/web/js/main.js
web/templates/forms/fields.html
web/templates/partial/case/edit-fir.html
web/templates/partial/case/fir.html
web/templates/web/domains/case/fir/add-fir-file.html
web/templates/web/domains/case/fir/add-fir-response-file.html
web/templates/web/domains/case/respond-fir.html
web/tests/domains/case/access/factories.py
web/tests/domains/case/test_views.py

Changes:
- Update FIR templates to add single files
- Add FIR views to redirect to correct template
- Add check_application_permission utility function

ICMSLST-665 Convert multifile to single file upload for FIR views.

---

mypy.ini
web/domains/case/_import/fa_oil/models.py
web/domains/country/views.py
web/models/mixins.py
web/views/actions.py
web/views/mixins.py

Other changes:
- enable check_untyped_defs flag
- exclude migrations from mypy checks for speed

ICMSLST-647 Fix non-bugs found by mypy.

---

web/templates/partial/case/import/fa-dfl/goods-list.html
web/templates/web/domains/case/import/manage/prepare-fa-dfl-response.html
web/templates/web/domains/case/import/manage/prepare-response.html
web/templates/web/domains/case/import/sanctions/edit_application.html

Screens touched: 
- Firearms and Ammunition (Deactivated Firearms Licence) 
- Response preparation (dfl goods section & common Endorsement section)
- Sanctions and Adhoc License Application

ICMSLST-707 & ICMSLST-708 Fix edit and delete action labels.

---

web/domains/case/_import/opt/forms.py
web/domains/case/_import/opt/models.py
web/domains/case/_import/opt/urls.py
web/domains/case/_import/opt/views.py
web/migrations/0065_add_opt.py
web/models/__init__.py
web/templates/partial/case/import/opt/sidebar.html
web/templates/web/domains/case/import/opt/add_supporting_document.html
web/templates/web/domains/case/import/opt/edit-further-questions-shared.html
web/templates/web/domains/case/import/opt/edit.html
web/templates/web/domains/case/import/partials/opt/documents_list.html

This adds the questions with file uploads.

ICMSLST-713 Add Further Questions to OPT editing (phase two).

---

web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/urls.py
web/domains/case/_import/fa_sil/views.py
web/domains/case/views.py
web/templates/web/domains/case/import/manage/fa-sil-edit-goods.html
web/templates/web/domains/case/import/manage/fa-sil-set-cover-letter.html
web/templates/web/domains/case/import/manage/prepare-fa-sil-response.html
web/templates/web/domains/case/import/manage/prepare-response.html

Changes:
- Add FA-SIL response preparation screen.
- Save endorcement when saving FA-SIL form.
- Add view to edit FA-SIL Goods.
- Add ability to set the cover letter.

ICMSLST-717 Add response preparation view for FA-SIL applications

---

web/domains/case/_import/fa/forms.py
web/domains/case/_import/fa/views.py
web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/models.py
web/domains/case/_import/fa_sil/views.py
web/domains/case/views.py
web/migrations/0062_add_silapplication.py
web/templates/forms/widgets/firearms/checkbox_select_table.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/fa-dfl/view.html
web/templates/web/domains/case/import/fa-sil/edit.html
web/templates/web/domains/case/import/fa-sil/goods/section1-boxes.html
web/templates/web/domains/case/import/fa-sil/goods/section2-boxes.html
web/templates/web/domains/case/import/fa-sil/goods/section5-boxes.html
web/templates/web/domains/case/import/fa-sil/goods/section582-obsolete-boxes.html
web/templates/web/domains/case/import/fa-sil/goods/section582-other-boxes.html
web/templates/web/domains/case/import/view_case.html
web/templates/web/domains/case/import/view_derogations.html
web/templates/web/domains/case/import/view_firearms_oil_case.html
web/templates/web/domains/case/import/view_firearms_sil_case.html
web/templates/web/domains/case/import/view_sanctions_and_adhoc_case.html

And add ability to view applications

ICMSLST-716 Add constabulary emails to SIL (ILB Admin)

---

web/domains/case/_import/derogations/forms.py
web/domains/case/_import/fa_dfl/forms.py
web/domains/case/_import/fa_oil/forms.py
web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/models.py
web/domains/case/_import/models.py
web/domains/case/_import/opt/forms.py
web/domains/case/_import/sanctions/forms.py
web/domains/case/_import/wood/forms.py
web/migrations/0001_initial.py
web/migrations/0062_add_silapplication.py
web/migrations/0064_silgoodssections.py

Allow only positive quantities
Move help texts, labels and choices from forms to models

ICMSLST-740 Move logic from SIL forms to models

---

web/domains/case/_import/opt/forms.py
web/domains/case/_import/opt/widgets.py
web/static/web/js/pages/opt-compensating-products.js
web/templates/web/domains/case/import/opt/edit-compensating-products.html

Changes:
- Added widget to filter commodities by correct group & category.
- Added some JS to clear the form when a category changes.
- Updated form clean method to ensure no invalid commodities are saved.

ICMSLST-739 Filter OPT Compensating products commodity codes correctly.

---

web/domains/case/views.py
web/templates/web/domains/case/import/opt/view.html

Other change:
- Fix a typo linking to the "Level of employment" section of the OPT app.

ICMSLST-747 Add Authorisation view to OPT applications.

---

docker-compose.yml
web/domains/case/_import/wood/forms.py
web/domains/case/_import/wood/models.py
web/domains/case/_import/wood/views.py
web/migrations/0039_woodquotaapplication.py
web/migrations/0060_alter_references.py

Also:
ICMSLST-654 Comment out selenium/chrome in docker-compose.yml.
We are not running the BDD tests at the moment, downloading/running these
is just wasting time and resources.

ICMSLST-654 Add missing validation to forms.

---

web/domains/case/_import/derogations/forms.py
web/domains/case/_import/derogations/views.py
web/domains/case/_import/fa_dfl/forms.py
web/domains/case/_import/fa_dfl/views.py
web/domains/case/_import/fa_oil/forms.py
web/domains/case/_import/fa_oil/views.py
web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/views.py
web/domains/case/_import/opt/forms.py
web/domains/case/_import/opt/views.py
web/domains/case/_import/sanctions/forms.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/textiles/urls.py
web/domains/case/_import/textiles/views.py
web/domains/case/_import/wood/forms.py
web/domains/case/_import/wood/views.py
web/domains/case/export/forms.py
web/domains/case/export/views.py
web/domains/case/forms.py
web/domains/firearms/forms.py
web/domains/firearms/views.py
web/domains/importer/views.py
web/domains/section5/forms.py
web/templates/partial/case/import/textiles/sidebar.html
web/templates/web/domains/case/import/textiles/submit.html

Also:
ICMSLST-755 Remove duplicated document / confirmation forms.
Remove duplicated forms, use the generic one from case/forms.py.

    ICMSLST-755 Add "submit" for Textiles application.

---

web/domains/case/views.py
web/templates/web/domains/case/import/sps/edit.html
web/templates/web/domains/case/import/textiles/edit.html
web/templates/web/domains/case/import/textiles/view.html

View the details of a submitted Textile application

ICMSLST-761 Add Textiles (Quota) view

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/fa/views.py
web/domains/case/_import/fa_oil/views.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/wood/views.py
web/domains/case/export/views.py
web/templates/web/domains/case/import/manage/prepare-wood-quota-response.html
web/templates/web/domains/case/import/sanctions/manage/sanction-email-box.html
web/templates/web/domains/case/import/sanctions/manage/sanction-emails.html
web/tests/domains/case/export/test_views.py

ICMSLST-782 Use check_application_permission in views

---

web/domains/case/_import/models.py
web/domains/case/_import/sps/forms.py
web/domains/case/_import/sps/models.py
web/migrations/0001_initial.py
web/migrations/0072_add_prior_surveillance.py
web/templates/partial/case/import/sidebar-create.html
web/templates/web/domains/case/import/sps/edit.html

Also tidy up import application create sidebar.

ICMSLST-605 Add application details for Prior Surveillance.

---

web/domains/case/_import/sps/forms.py
web/domains/case/_import/sps/models.py
web/domains/case/_import/sps/views.py
web/domains/case/views.py
web/migrations/0072_add_prior_surveillance.py
web/models/__init__.py
web/templates/web/domains/case/import/sps/edit.html
web/templates/web/domains/case/import/sps/view.html
web/templates/web/domains/case/view_case.html

Also rename value_euro to value_eur for consistency with value_gbp.

ICMSLST-604 Implement "view application" for Prior Surveillance.

---

web/domains/case/_import/textiles/forms.py
web/domains/case/_import/textiles/models.py
web/domains/case/_import/textiles/urls.py
web/domains/case/_import/textiles/views.py
web/domains/case/views.py
web/management/commands/add_test_data.py
web/migrations/0071_add_textiles.py
web/templates/display/fields.html
web/templates/web/domains/case/import/manage/prepare-response.html
web/templates/web/domains/case/import/manage/prepare-textiles-quota-response.html
web/templates/web/domains/case/import/manage/response-prep-textiles-edit-form.html
web/templates/web/domains/case/view_case.html
web/tests/domains/case/_import/textiles/test_admin_views.py
web/tests/domains/case/_import/textiles/test_views.py

* Add view for response preparation for textiles
* Include link to edit goods using `GoodsTextilesLicenceForm`

ICMSLST-757 Add Textiles (Quota) response preparation view

---

web/domains/case/views/views_misc.py
web/domains/workbasket/views.py
web/templates/web/domains/case/ack-notification.html
web/templates/web/domains/case/document-packs.html
web/templates/web/domains/case/manage/document-packs-list.html
web/tests/domains/case/test_models.py

When application is made by an agent:
- Primary recipients are the agent's contacts.
- Copy recipients are the org's contacts
ICMSLST-1047 Add 'View Notification' for importer
Importer's contacts can view the notification when it's acknowledged by
an agent.

ICMSLST-1046 Add agent's contacts for 'authorise document'

---

web/domains/case/forms.py
web/domains/case/types.py
web/domains/case/views/views_email.py
web/templates/web/domains/case/manage/edit-case-email.html

- Make recipient for BEIS and HSE editable
- Add all the attachments by default for BEIS email

ICMSLST-1120 Update BEIS recipient and attachments for case email

---

README.md
config/settings/non_prod_base.py
docker-compose.yml
web/middleware/common.py
web/utils/db.py

Enable it by setting SHOW_DB_QUERIES=True in your .env file.

ICMSLST-643 Add middleware that prints all DB queries made.

---

web/domains/case/forms_search.py
web/templates/web/domains/case/search/export/search-form-fields.html
web/templates/web/domains/case/search/results.html

Also updated several labels to match legacy.

ICMSLST-976 Add advanced certificate application search fields.

---

web/domains/case/views/views_prepare_response.py
web/static/web/js/pages/approval-response.js

Other changes:
- Clear refuse reason when Approve is selected.

ICMSLST-1194 Update Response Prep view to retain decision form value.

---

web/domains/case/views/views_search.py
web/templates/web/domains/case/search/export/actions.html
web/tests/utils/search/test_search.py
web/tests/utils/search/test_search_actions.py
web/utils/search/api.py
web/utils/search/utils.py

Other changes:
- Pass user to the search code and add placeholder comments for implementing ICMSLST-1240

ICMSLST-1207 Add actions for results on export application search screen.

---

web/domains/case/models.py
web/domains/case/utils.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_search.py
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/variations/macros.html
web/tests/domains/case/test_utils.py

Changes:
- Add function to update case reference when a vr is requested.
- Annotate variation requests with row number.
- Display count of open and total variation requests.

ICMSLST-1287 Add variation number to case reference.

---

Makefile
README.md
run-tests.sh

Also fix error in testing section of README.md

Update run-tests.sh to not run coverage by default.

---

.gitignore
config/settings/base.py
pii-ner-exclude.txt
requirements-prod.txt
scripts/entry.sh

- Include the settings for data migration
- Install oracle instant client on prod deployment
- Add cx-Oracle library to prod requirements

ICMSLST-1379 Set up app for data migration

---

pii-ner-exclude.txt
web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/domains/case/urls.py
web/domains/case/views/mixins.py
web/domains/case/views/views_pdf.py
web/templates/web/domains/case/document-list.html
web/templates/web/domains/case/manage/prepare-response.html
web/tests/domains/case/_import/test_views.py
web/utils/pdf/__init__.py
web/utils/pdf/generator.py
web/utils/pdf/types.py
web/utils/pdf/utils.py

This will be extended to support all types of PDFs we need to create.

ICMSLST-1420 Refactor existing preview licence and cover letter views.

---

.coveragerc
Makefile
pii-ner-exclude.txt
requirements-dev.txt
run-tests.sh
web/domains/case/_import/fa_sil/views.py
web/domains/case/views/views_pdf.py
web/static/web/css/pdfs/fa-common-licence-style.css
web/static/web/css/pdfs/fa-paper-licence-quantity-table-style.css
web/templates/pdf/import/fa-dfl-licence-preview.html
web/templates/pdf/import/fa-licence-base.html
web/templates/pdf/import/fa-paper-licence-quantity-table.html
web/templates/pdf/import/fa-sil-licence-pre-sign.html
web/templates/pdf/import/fa-sil-licence-preview.html
web/tests/application_utils.py
web/tests/conftest.py
web/tests/domains/case/views/test_views_pdf.py
web/tests/utils/pdf/conftest.py
web/tests/utils/pdf/test_generator.py
web/tests/utils/pdf/test_utils.py
web/utils/pdf/generator.py
web/utils/pdf/utils.py

Other changes:
- Exclude "if TYPE_CHECKING" blocks from coverage report
- Add minimum coverage check to CI pipeline

ICMSLST-1409 Add preview and pre-sign versions of FA SIL licence.

---

Makefile
data_migration/management/commands/export_from_v1.py
data_migration/management/commands/import_v1_data.py
data_migration/management/commands/utils/db.py
data_migration/management/commands/utils/format.py
data_migration/models/user/user.py
data_migration/tests/test_export.py
data_migration/tests/test_import.py
data_migration/tests/test_utils.py
pii-ner-exclude.txt
requirements-base.txt
requirements-prod.txt

```
Name                                                                  Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------------------------------------------------
data_migration/management/commands/export_from_v1.py                     72     10     32      1    80%   100, 114-143
data_migration/management/commands/import_v1_data.py                     46      0     18      0   100%
data_migration/management/commands/utils/db.py                           19      0      0      0   100%
data_migration/management/commands/utils/format.py                       15      0     10      0   100%
data_migration/models/base.py                                            50      1     20      0    99%   86 …
```

ICMSLST-1451 Test coverage for data_migration app

---

pii-ner-exclude.txt
web/domains/case/models.py
web/domains/case/views/views_misc.py
web/templates/web/domains/case/import/manage/preview-licence.html
web/tests/domains/case/views/test_views_misc.py
web/tests/domains/case/views/test_views_pdf.py
web/tests/utils/pdf/test_generator.py
web/tests/utils/pdf/test_utils.py
web/utils/pdf/utils.py

Other changes:
- ICMSLST-1445: Set licence reference in pdf template

ICMSLST-1441 Set import application document references when authorising.

---

web/tests/utils/search/test_search.py
web/utils/search/api.py
web/utils/search/app_data.py

Changes:
- Add export application certificate references to results.
- Add export application certificate references wildcard search.

ICMSLST-1443 & ICMSLST-1444

---

pii-ner-exclude.txt
web/domains/case/_import/views.py
web/domains/case/urls.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_pdf.py
web/templates/web/domains/case/ack-notification.html
web/templates/web/domains/case/document-list.html
web/templates/web/domains/case/manage/imi-case-detail.html
web/tests/utils/search/test_search.py
web/utils/search/api.py
web/utils/search/app_data.py

Changes:
- Refactor view_case_document to take a casedocumentreference_pk arg.
- Update search queries to retrieve required case document download args.
- Add download case file functionality to several views.
- Add links to revisit code for export application documents.

ICMSLST-1500 Add download case document links to several views.

---

pii-ner-exclude.txt
web/domains/case/urls.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_pdf.py
web/domains/workbasket/actions/ilb_admin_actions.py
web/tests/domains/case/views/test_views_misc.py
web/tests/domains/case/views/test_views_pdf.py

Other changes:
Removed incorrect permission checking for several views.
The views are for ILB Admin's only.
The previous code allowed anyone with access to the application
to access those views.

ICMSLST-1531 Add Recreate Case Documents view.

---

web/domains/case/_import/fa/views.py
web/templates/web/domains/case/import/fa/import-contacts/list.html
web/tests/domains/case/_import/fa/test_views.py

Changes:
- Add Delete action to list view when creating an application.
- Update redirect links after saving a firearms contact.
- Add tests for several views.

ICMSLST-1454 Add ILB feedback changes for firearms contact list and forms.

---

web/domains/case/_import/fa_sil/views.py
web/domains/case/views/views_view_case.py

Also fix certificates not being checked when submitting fa-sil application.

ICMSLST-1551 Fix section 5 authorities not showing on view application.

---

config/settings/base.py
docker-compose.yml
pii-ner-exclude.txt
web/domains/case/access/approval/models.py
web/domains/case/access/models.py
web/domains/case/models.py
web/domains/case/views/views_fir.py
web/domains/workbasket/actions/applicant_actions.py
web/domains/workbasket/actions/ilb_admin_actions.py
web/domains/workbasket/base.py
web/domains/workbasket/views.py
web/templates/web/domains/workbasket/workbasket.html
web/tests/domains/case/test_models.py
web/utils/__init__.py

Changes:
- Optimise Admin workbasket query
- Optimise Applicant workbasket query
- Order workbasket records by "order_datetime"
- Add pagination to workbasket.
- ICMSLST-1564 Fix exception thrown on manage_fir view for Access records.

ICMSLST-1087 Optimise both admin and applicant workbasket queries.

---

web/domains/case/_import/opt/forms.py
web/domains/case/_import/opt/views.py
web/templates/partial/case/sidebar.html

Views changed:
- Application Details
- Compensating Products
- Temporary Exported Goods
- Further Questions

ICMSLST-1517 Add partial form saving to several OPT views.

---

web/domains/case/export/views.py

ICMSLST-1003 Update logic that shows the Add Product link.

---

web/domains/case/export/forms.py
web/domains/case/export/views.py

Changes:
- ICMSLST-1565 Filter product legislation query based on exporter office.
- ICMSLST-1568 Update create CFS application message.

ICMSLST-1565/1568 CFS application feedback changes

---

web/domains/country/views.py
web/templates/web/domains/country/list.html

- ICMSLST-1561 Update success URL to redirect to edit translation view.
- ICMSLST-1559 Remove remaining reference to Country Set.

ICMSLST-1561/ ICMSLST-1559 Minor changes to country admin pages.

---

web/domains/case/export/forms.py

Add extra logic to prevent user from saving a value that will never be valid.

ICMSLST-1611 Add form validation to COM edit form.

---

web/domains/section5/filters.py
web/domains/section5/views.py

Other changes:
- Order queryset by active status and date created.
- Add is_active filter to list view

ICMSLST-1347 Fix edit url not found bug.

---

web/auth/views.py
web/domains/case/_import/derogations/views.py
web/domains/case/_import/fa_dfl/views.py
web/domains/case/_import/fa_oil/views.py
web/domains/case/_import/fa_sil/views.py
web/domains/case/_import/ironsteel/views.py
web/domains/case/_import/opt/views.py
web/domains/case/_import/textiles/views.py
web/domains/case/_import/wood/views.py
web/domains/case/app_checks.py
web/domains/case/urls.py
web/domains/case/views/views_fir.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_note.py
web/domains/case/views/views_prepare_response.py
web/domains/case/views/views_update_request.py
web/templates/partial/case/export/sidebar-management.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/manage/list-update-requests.html
web/tests/domains/case/views/test_views_update_request.py
web/tests/helpers.py

Further information requests, Case Notes and Application Updates should all work in a similar way.
Also updated a load of incorrect `if request.POST` lines.

ICMSLST-1376 / ICMSLST-1587 Updates to FIR / Case Notes and Application Updates

---

config/settings/local.py
web/domains/chief/client.py
web/management/commands/query_icms_hmrc.py

Other changes:
- Update local logging settings to remove all json based logging.

ICMSLST-1665 Fix hawk client to support get requests correctly.

---

pii-ner-exclude.txt
web/domains/case/_import/fa_sil/views.py
web/domains/case/_import/models.py
web/domains/case/_import/views.py
web/domains/case/app_checks.py
web/domains/case/export/models.py
web/domains/case/services/reference.py
web/domains/case/tasks.py
web/domains/case/types.py
web/domains/case/utils.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_pdf.py
web/domains/case/views/views_prepare_response.py
web/domains/chief/serializers.py
web/domains/workbasket/actions/applicant_actions.py
web/tests/conftest.py
web/tests/domains/case/services/test_reference.py
web/tests/domains/case/test_utils.py
web/tests/domains/case/views/test_views_misc.py
web/tests/domains/case/views/test_views_pdf.py
web/tests/domains/case/views/test_views_search.py
web/tests/domains/case/views/test_views_variation_request.py
web/tests/utils/pdf/test_generator.py
web/utils/pdf/generator.py
web/utils/pdf/utils.py
web/utils/search/api.py

Changes:
- Remove confusing property that isn't needed as the pdf generation code is already using the licence start date.
- Refactor method to get latest licence or certificate

ICMSLST-1744 Fix Issue date on licence generation.

---

pii-ner-exclude.txt
web/end_to_end/test_create_export_com_application.py
web/end_to_end/test_create_export_gmp_application.py
web/templates/web/domains/case/export/gmp-edit-brand.html

Other changes:
- Fix incorrect form encoding on GMPBrand form.

ICMSLST-1805 Add end to end test for GMP export application.

---

pii-ner-exclude.txt
web/end_to_end/test_create_export_cfs_application.py
web/end_to_end/utils.py
web/templates/web/domains/case/export/cfs-edit-product-child.html
web/templates/web/domains/case/export/cfs-edit-product.html
web/templates/web/domains/case/export/cfs-edit.html

Other changes:
- Fix incorrect form encoding on several CFS forms.

ICMSLST-1804 Add end to end test for CFS export application.

---

pii-ner-exclude.txt
web/domains/workbasket/actions/ilb_admin_actions.py
web/domains/workbasket/views.py
web/tests/domains/workbasket/actions/test_applicant_actions.py
web/tests/domains/workbasket/actions/test_ilb_admin_actions.py

Also add case worker check for several management views.

ICMSLST-1592 Add admin workbasket action for managing withdrawals.

---

web/tests/utils/search/test_search_actions.py
web/utils/search/api.py

Fixes this error:
TypeError - can't compare offset-naive and offset-aware datetimes.

ICMSLST-1901 Add timezone to fix comparing naive and aware datetimes.

---

pii-ner-exclude.txt
web/domains/case/_import/fa/views.py
web/domains/case/urls.py
web/domains/case/views/views_case_history.py
web/templates/partial/case/export/sidebar-management.html
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/export/cfs-view.html
web/templates/web/domains/case/import/fa-sil/view.html
web/templates/web/domains/case/import/fa/provide-report/report-info.html
web/templates/web/domains/case/import/opt/view.html
web/templates/web/domains/case/view_case.html
web/tests/helpers.py

Also fix all applications to show correct sidebar.

ICMSLST-1910 Fix link to case history for all application types.

---

pii-ner-exclude.txt
web/jinja2.py
web/perm_harness/views.py
web/templates/web/perm_harness/index.html

Changes:
- Add get_user_obj_perms to jinja env globals.
- Update test data for permission test harness view.
- Update permission test harness with get_user_obj_perms example.

ICMSLST-1934 Add jinja function to load a users object perms.

---

.pre-commit-config.yaml
README.md
pii-ner-exclude.txt
requirements-dev.txt
web/domains/chief/serializers.py
web/templates/web/domains/case/import/manage/preview-licence.html

- Upgrade mypy to 1.1.1.
- Update README to correctly document how to set up the application.
- Add missing closing ul to the preview-licence.html template.

Several unrelated changes

---

config/settings/production.py
pii-ner-exclude.txt
requirements-base.txt
web/utils/sentry.py

https://cve.report/CVE-2023-28117

ICMSLST-1952 Fix CVE-2023-28117.

---

pii-ner-exclude.txt
web/domains/case/_import/forms.py
web/domains/case/_import/views.py
web/domains/template/context.py
web/domains/template/forms.py
web/domains/template/utils.py
web/static/web/css/components/text-editor.css
web/static/web/js/components/text-editor.js
web/templates/web/domains/case/import/manage/edit-cover-letter.html
web/templates/web/domains/case/manage/prepare-response.html
web/tests/domains/case/_import/test_forms.py
web/tests/domains/template/test_forms.py
web/tests/domains/template/test_utils.py

Placeholders in cover letter editor and cover letter template are validated against a predefined list

ICMSLST-1921 Validate cover letter template placeholders

---

pii-ner-exclude.txt
web/domains/case/views/views_search.py
web/permissions/service.py
web/tests/utils/search/test_search_actions.py
web/utils/search/actions.py
web/utils/search/api.py
web/utils/search/types.py
web/utils/search/utils.py

Changes:
- Refactor importer search actions to check object permissions.
- Refactor exporter search actions to check object permissions.
- Extend unittests to check org user permissions.

ICMSLST-1956 Update search row actions to check user org permissions.

---

web/domains/case/_import/derogations/views.py
web/domains/case/_import/ironsteel/views.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/sps/views.py
web/domains/case/_import/views.py
web/domains/case/_import/wood/views.py
web/domains/case/utils.py

Replace two different view file functions with correct function (they all check permissions the same way now).

Refactor all applicant views to use view_application_file function.

---

web/domains/case/export/forms.py
web/domains/case/export/views.py
web/tests/conftest.py

Changes:
- Update all export views
- Fix export agent search bug on create application form.
- Update exporters / agents shown in create export app form.
- Update exporter_client to use a user with correct permissions.

ICMSLST-1737 Update export views to use new permissions.

---

web/domains/case/views/mixins.py
web/domains/case/views/views_misc.py

Views updated:
- cancel_case
- withdraw_case
- archive_withdrawal
- ViewIssuedCaseDocumentsView
- ClearIssuedCaseDocumentsFromWorkbasket

ICMSLST-2004 Update several applicant views to use new permissions.

---

web/domains/case/_import/models.py
web/domains/case/export/models.py
web/domains/case/forms.py
web/domains/case/models.py
web/domains/case/views/views_misc.py
web/permissions/service.py

Other changes:
- Update contacts that appear on PDFS before ICMSLST-2006 is started.

ICMSLST-2005 Update application_contacts to use new permissions.

---

pii-ner-exclude.txt
web/domains/case/views/views_email.py
web/domains/template/context.py
web/tests/application_utils.py
web/tests/conftest.py
web/tests/domains/template/test_context.py
web/tests/notify/test_utils.py

Sanction emails aren't currently used in the system (and probably never will be) but implementing for completeness

ICMSLST-1970 Sanctions Email

---

.pre-commit-config.yaml
pii-ner-exclude.txt
web/domains/case/_import/models.py
web/domains/case/export/models.py
web/domains/workbasket/views.py
web/templates/web/domains/case/import_licence_history.html
web/tests/conftest.py
web/tests/domains/case/_import/test_models.py
web/tests/domains/case/export/test_models.py
web/tests/domains/workbasket/test_views.py

Includes fixes for the following:
- ICMSLST-1600 Refuse case - Refuse case - remove from ILB workbasket once refused.
- ICMSLST-1601 Refuse case - use Refused status when a case has been refused.
- ICMSLST-1602 Refuse case - Refuse case - show reason for refusal to applicant.

Refused Case improvements

---

web/domains/case/access/approval/views.py
web/domains/case/services/case_progress.py
web/domains/workbasket/row.py

Changes:
- Load correct workbasket row for approval requests.
- Check correct status when taking ownership of approval request.
- Check correct status when releasing ownership of approval request.

ICMSLST-1789 Fix several org approval request bugs.

---

pii-ner-exclude.txt
web/domains/case/tasks.py
web/domains/case/views/views_misc.py
web/domains/chief/utils.py
web/notify/notify.py
web/templates/email/application/approved.html
web/templates/email/import/constabulary_notification.html
web/templates/email/import/fa_supplementary.html
web/tests/conftest.py
web/tests/domains/case/_import/test_models.py
web/tests/domains/case/_import/test_views.py
web/tests/domains/case/views/test_views_case_history.py
web/tests/domains/case/views/test_views_misc.py
web/tests/domains/case/views/test_views_search.py
web/tests/domains/chief/test_client.py
web/tests/domains/workbasket/actions/test_applicant_actions.py
web/tests/helpers.py
web/tests/notify/test_notify.py

* Complete applications sends a notification to application contacts that the documents are available in ICMS
* Complete FA applications also send a notification to complete supplementary reporting
* Complete DFL applications also send the licence documents to the constabulary contact with a notification of the approval

ICMSLST-1982 Case Complete Notifications

---

pii-ner-exclude.txt
web/domains/workbasket/views.py

All workbasket actions and permission will be revisited in ICMSLST-1947.

ICMSLST-2029 Update permission checked in workbasket for linked orgs.

---

pii-ner-exclude.txt
web/domains/case/access/urls.py
web/domains/case/access/views.py
web/templates/partial/case/access/sidebar-management.html
web/templates/web/domains/case/access/access-request-history.html
web/templates/web/domains/case/access/case-user-base.html
web/templates/web/domains/case/access/list-exporter.html
web/templates/web/domains/case/access/list-importer.html
web/templates/web/domains/case/access/management-access-approval.html
web/templates/web/domains/case/access/management.html
web/templates/web/domains/case/access/partials/access-request-list.html
web/templates/web/domains/case/access/partials/access-request-section.html
web/templates/web/domains/case/access/partials/approval-request-section.html
web/tests/domains/case/access/test_views.py

Changes:
- Add access request history view.
- Add reusable access-request-section.html file to display access requests.
- Add reusable approval-request-section.html to display approval requests.
- Refactor several views to use reusable templates.
- Display reference instead of pk for access requests.
- Add tests for AccessRequestHistoryView.

ICMSLST-2039 Several fixes for access requests management.

---

pii-ner-exclude.txt
web/domains/case/views/views_fir.py
web/domains/case/views/views_update_request.py
web/domains/template/context.py
web/domains/template/utils.py
web/notify/email.py
web/notify/notify.py
web/notify/utils.py
web/templates/email/base.html
web/templates/email/fir/requested.html
web/templates/email/fir/responded.html
web/tests/domains/case/views/test_views_fir.py
web/tests/domains/template/test_utils.py
web/tests/helpers.py
web/tests/notify/test_email.py
web/tests/notify/test_notify.py

* Create initial further information request from the database templates.
* Send the fir email to application contacts
* Send the fir withdrawn notification to application contacts
* Send the fir responded notification to the case officer

ICMSLST-1964 Create draft FIR from template

---

web/end_to_end/case/import_app/test_create_fa_dfl_application.py
web/templates/web/domains/case/import_licence_history.html

- Fix broken end to end test.
- Fix case history document name for sanctions licences.

Unrelated bug fixes

---

data_migration/management/commands/_types.py
data_migration/management/commands/check_data_counts.py
data_migration/management/commands/config/data_counts.py
data_migration/management/commands/config/post_migrate.py
data_migration/management/commands/post_migration.py
data_migration/models/user/user.py
data_migration/queries/__init__.py
data_migration/queries/permissions.py
data_migration/tests/test_e2e.py
data_migration/tests/utils/user_data.py
pii-ner-exclude.txt

* Post migration management command to create permissions (must be called after create_icms_groups)
* Adds users to ILB Case Officer, Home Office Case Officer and NCA Case Officer groups
* Added more data checks to see if users in groups is as expected

ICMSLST-2089 Data migration command to apply case officer groups

---

web/notify/notify.py
web/tests/notify/test_notify.py

Fix expiring section 5 authority notification to not send the notification if there are no expiring section 5 authorities

ICMSLST-2048 Fix Expiring Section 5 Authority Notification

---

pii-ner-exclude.txt
web/tests/application_utils.py
web/tests/auth/auth.py
web/tests/conftest.py
web/tests/domains/workbasket/test_views.py

Changes:
- Add workbasket tests for different users and application states.
- Add the following fixtures:
- importer_agent_client
- exporter_agent_client
- ilb_admin_two_client
- fa_dfl_agent_app_in_progress
- fa_dfl_agent_app_submitted
- com_agent_app_in_progress
- com_agent_app_submitted

ICMSLST-2163 Add workbasket tests.

---

pii-ner-exclude.txt
web/domains/case/access/approval/forms.py
web/domains/case/access/approval/models.py
web/domains/case/access/approval/views.py
web/domains/case/access/models.py
web/domains/case/services/case_progress.py
web/domains/workbasket/app_data.py
web/notify/email.py
web/templates/email/access/approval/completed.html
web/templates/email/access/approval/exporter/opened.html
web/templates/email/access/approval/importer/opened.html
web/tests/domains/case/access/approval/test_views.py
web/tests/helpers.py
web/tests/notify/test_email.py
web/tests/notify/test_notify.py

Sends Access Approval emails when an Approval is created and when a response has been received.
Also updated the `Responses` and `Statuses` on the model to be TypedTextChoices

ICMSLST-2034 Access Approval Request emails

---

data_migration/management/commands/_types.py
data_migration/management/commands/check_data_counts.py
data_migration/management/commands/config/data_counts.py
data_migration/queries/export_application/export.py
data_migration/queries/import_application/licence.py
pii-ner-exclude.txt

- Add a check for files with duplicate paths
- Fix queries for data migration licence and certificates so pdf file extension is included in filenames

Data migration fix licence and certificate document filenames

---

.circleci/config.yml
.env.example
config/settings/base.py
config/settings/test.py
docker-compose.yml
pii-ner-exclude.txt
requirements-base.txt
web/permissions/service.py
web/registration/views.py
web/urls.py

Changes:
- Add staff-sso-client.
- Added environment variable to enable / disable staff-sso integration.
- Set correct backend when calling User.objects.with_perm to fix ValueError exception being raised when multiple authentication backends are set.

ICMSLST-2065 Add staff-sso-client to ICMS.

---

config/settings/base.py
pii-ner-exclude.txt
pyproject.toml
web/auth/backends.py
web/auth/types.py
web/tests/auth/test_backends.py

Changes:
- Migrates legacy users after successful staff-sso login.
- ICMSLST-2212 Fix missing Email record for staff-sso users.

ICMSLST-2211 Add ICMSStaffSSOBackend class.

---

config/settings/base.py
config/settings/local.py
config/settings/test.py
docker-compose.yml

Other changes:
- Remove several commented out lines in docker-compose.yml.

ICMSLST-2325 Silence log messages generated by WeasyPrint.

---

requirements-base.txt

Tested every page that uses filters, everything still works.

ICMSLST-1826 Upgrade Django Filter.

---

web/domains/case/export/forms.py

Refactor base class attributes that rely on the form application instance.

ICMSLST-2280 Fix COM application template.

---

pii-ner-exclude.txt
web/domains/case/export/forms.py
web/templates/web/domains/case/export/cfs-edit-schedule.html
web/templates/web/domains/case/export/cfs-view.html

Changes:
- Require address value when postcode is set.
- Update formatting on several CFS fields to remove extra padding.

ICMSLST-2310 Fix CFSManufacturerDetailsForm form validation.

---

Dockerfile
documentation/playwright.md
pii-ner-exclude.txt
web/end_to_end/case/import_app/test_create_sanctions_application.py

- Upgrade docker python version
- Fix sanctions playwright test

Upgrade python version in docker

---

.gitignore
Makefile
config/settings/base.py
config/settings/non_prod_base.py
pii-ner-exclude.txt
web/domains/case/tasks.py
web/domains/case/urls.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_pdf.py
web/management/commands/generate_static_pdf.py
web/static/web/css/pdfs/cfs-letter-style.css
web/templates/pdf/export/cfs-letter.html
web/templates/pdf/import/cover-letter.html
web/templates/web/domains/case/document-list.html
web/tests/domains/case/views/test_views_misc.py
web/tests/management/commands/test_generate_static_pdf.py
web/tests/utils/pdf/conftest.py
web/tests/utils/pdf/test_generator.py
web/tests/utils/pdf/test_utils.py
web/types.py
web/types.pyi
web/utils/pdf/__init__.py
web/utils/pdf/generator.py
web/utils/pdf/utils.py

* CFS cover letter generated with management command `./manage.py generate_static_pdf`
* Link for the cfs cover letter will only be displayed after a cover letter has been generated

ICMSLST-2296 Generate CFS Cover Letter PDF

---

pii-ner-exclude.txt
web/domains/mailshot/forms.py
web/domains/mailshot/urls.py
web/domains/mailshot/views.py
web/templates/web/domains/mailshot/edit.html
web/tests/domains/mailshot/test_views.py
web/views/views.py

Changes:
- ICMSLST-1252 Refactor Edit, Cancel and Publish mailshot views.
- ICMSLST-1308 Change empty label for Status filter.
- ICMSLST-1309 Fix latest_version label and default filter value.

ICMSLST-1252|1308|1309| Several Mailshot feedback items

---

pii-ner-exclude.txt
web/notify/email.py
web/notify/notify.py
web/tests/domains/workbasket/test_views.py

Also fix a warning when running unittests relating to naive datetimes.

ICMSLST-1848 Fix mailshot email sending logic.

---

web/templates/web/domains/case/import/imi/list.html

Screen with no IMI Cases:
Screen with IMI Cases:

ICMSLST-1315 Add missing info banner when there are no IMI cases.

---

pii-ner-exclude.txt
web/flow/models.py
web/templates/partial/case/sidebar.html
web/tests/flow/test_models.py

Screenshot showing where link is displayed:
Same for export apps:

ICMSLST-1603 Show summary of app type instead of "Application Details".

---

pii-ner-exclude.txt
web/domains/case/views/views_email.py
web/templates/web/domains/case/manage/case-emails.html
web/tests/domains/case/views/test_views_email.py

ICMSLST-1365 Update HSE email header & subheader.

---

web/domains/exporter/forms.py
web/domains/exporter/views.py
web/domains/importer/views.py

Changes:
- Add status filter.
- Update default filter value on Importer & Exporter list views.

ICMSLST-1314 Add Exporter list Status filter.

---

pii-ner-exclude.txt
web/domains/workbasket/app_data.py
web/permissions/service.py
web/templates/partial/agents-base.html
web/templates/web/domains/importer/view.html
web/tests/permissions/test_service.py

Changes:
- Fix view organisation permissions when viewing agents.
- Fix open approval request annotations.

ICMSLST-2407 Fix view organisation permissions when viewing agents.

---

pii-ner-exclude.txt
web/domains/case/urls.py
web/domains/case/views/views_documents.py
web/domains/case/views/views_misc.py
web/mail/messages.py
web/mail/url_helpers.py
web/management/commands/create_icms_groups.py
web/migrations/0001_initial.py
web/permissions/perms.py
web/templates/web/domains/case/view-case-documents.html
web/tests/application_utils.py
web/tests/conftest.py
web/tests/domains/case/views/test_views_documents.py
web/tests/helpers.py
web/tests/mail/test_emails.py
web/tests/mail/test_url_helpers.py

To test the view
- Create a DFL application setting constabulary as Nottingham
- Approve application
- Click link in  Automatic Notification email (login as con_user)
- View and download documents

ICMSLST-2393 - View for constabularies to see issued documents

---

Makefile
pii-ner-exclude.txt
scripts/reset-local-docker-db
web/management/commands/add_dummy_data.py
web/management/commands/add_test_data.py
web/static/web/js/components/signature.js

- Adds a dummy Signature object for non prod environments
- Fixes RevokeObjectUrl call in the preview when changing a file in Add Signature

ICMSLST-2431 Create dummy active signature for non prod environments

---

web/templates/web/domains/case/import/fa-sil/edit.html

changed Misc -> Additional information on the SIL import form to make it clearer

ICMSLST-1250 - SIIL import form copy changes

---

pii-ner-exclude.txt
web/domains/constabulary/forms.py
web/templates/web/domains/case/manage/manage.html
web/templates/web/domains/constabulary/list.html
web/tests/domains/constabulary/test_forms.py

Implemented typeahead for constabulary search form using ModelSelect2Widget

ICMSLST-1825 - Typeahead name input for constabulary search

---

README.md
config/env.py
config/settings.py
pii-ner-exclude.txt
requirements-base.txt
web/middleware/common.py
web/templates/base.html
web/templates/partial/offices/formset-script.html
web/templates/web/domains/chief/_base.html
web/templates/web/domains/template/create-cfs-declaration-translation.html
web/templates/web/domains/template/edit.html
web/templates/web/domains/template/list.html
web/templates/web/search-companies.html
web/tests/views/test_views.py

Added CSP headers via django-csp-middleware
Added nonces to all script elements
Added x-permitted-cross-domain-policy header
Added tests

ICMSLST-2422 - CSP headers

---

pyproject.toml
requirements-base.txt
web/domains/checker/views.py
web/static/web/css/components/signature.css
web/static/web/css/pdfs/certificate-style.css
web/templates/pdf/export/certificate-base.html
web/templates/web/domains/signature/macros.html
web/tests/utils/pdf/test_generator.py
web/utils/pdf/utils.py

- Add QR Code to certificate documents.
- QR code only appears when not viewing in preview mode

ICMSLST-696 Adding QR code to certificate documents

---

config/settings.py
web/templates/partial/js_constants.html
web/templates/web/domains/template/edit.html

ICMSLST-2422
Adding some missing CSP values, such as cloudflare and IMAGE-SRC

ICMSLST-2422 - CSP fixes

---

pii-ner-exclude.txt
web/domains/user/forms.py
web/domains/user/urls.py
web/domains/user/views.py
web/middleware/one_login.py
web/templates/web/domains/user/detail.html
web/templates/web/domains/user/user_add_related.html
web/templates/web/domains/user/user_edit.html
web/templates/web/domains/user/user_edit_related.html
web/templates/web/menu/menu.html
web/tests/domains/user/test_forms.py
web/tests/domains/user/test_views.py

Changes:
- Add UserUpdateView.
- Add UserCreateTelephoneView.
- Add UserUpdateTelephoneView.
- Add UserDeleteTelephoneView.
- Add UserCreateEmailView.
- Add UserUpdateEmailView.
- Add UserDeleteEmailView.
- Add UserDetailView for an ILB Admin to view readonly user data.
- Replace links to current-user-details to use user-edit view instead.
- Add basic permission tests for each new view.

ICMSLST-2440 Add views to allow a user to edit personal data in ICMS. 

---

web/domains/checker/views.py

Added django-ratelimit to PDF checker view.

ICMSLST-2406 - Rate-limiting PDF checker view

---

.env.circleci
Makefile
config/env.py
config/settings.py
pii-ner-exclude.txt
pyproject.toml
requirements-base.txt

Environment variables are loaded via CloudFoundryEnvironment or DBTPlatformEnvironment.
settings.py remains agnostic to the environment in which it is running.
When building the container image the fake environment variables in .env.circleci are used to ensure there are no validation errors.

Add support for running ICMS on DBT Platform. 

---

config/settings.py
config/settings_local.py
config/settings_test.py
pii-ner-exclude.txt
pyproject.toml
requirements-base.txt
web/domains/case/_import/sanctions/views.py
web/domains/case/access/models.py
web/domains/case/fir/forms.py
web/domains/country/views.py
web/domains/firearms/views.py
web/domains/importer/views.py
web/domains/mailshot/forms.py
web/forms/mixins.py
web/mail/backends.py
web/menu/menu.py
web/utils/companieshouse.py
web/views/mixins.py

Changes:
- Configure LOGGING setting with two handlers (console and asim).
- Add django_log_formatter_asim package.
- Remove structlog package.
- Remove django_structlog package.
- Fix imports to use logging package.

ICMSLST-2491 Add django_log_formatter_asim to work on DBT Platform.

---

web/static/web/css/pdfs/certificate-style.css
web/static/web/css/pdfs/licence-and-certificate-common-style.css
web/templates/pdf/shared/certificate-base.html
web/templates/web/domains/signature/macros.html
web/tests/domains/case/_import/test_views.py

Adding DBT logo watermark to certificate PDFs

ICMSLST-2439

---

config/settings.py
config/settings_local.py

Have the console handler be the default for readability and set to asim when running in the DBT Platform.

ICMSLST-2491 Update logging settings.

---

pytest.ini
web/utils/pdf/signer.py

ICMSLST-2509 Fix TypeError bug in pdf/signer.py.

---

data_migration/queries/case.py
data_migration/utils/xml_parser/case.py

Data Migration - Fix missing withdraw and endorsement fields

---

.pre-commit-config.yaml
config/gunicorn.py
config/urls.py
docker-compose.yml
local_deployment/Dockerfile
pii-ner-exclude.txt
requirements-base.txt
requirements-dev.txt
web/admin.py
web/auth/fox_hasher.py
web/domains/case/export/views.py
web/domains/chief/serializers.py
web/domains/template/context.py
web/domains/workbasket/row.py
web/reports/views.py
web/tests/domains/cat/test_models.py
web/tests/domains/constabulary/test_views.py
web/utils/search/actions.py

Changes:
- Update docker-compose.yml postgres image.
- Add psycopg[c] package.
- Add psycopg[c] build dependencies to Dockerfile.
- Remove psycogreen from gunicorn config as it applies to psycopg2.
- Add link to ICMSLST-2520 and comment out test with the bug.
- Upgrade black to latest version (this formats several files)

ICMSLST-2411 Upgrade to Postgres 16.1

---

web/templates/pdf/shared/fa-licence-base.html

ICMSLST-2478
Fixing address case in FA licences

ICMSLST-2478 - Uppercasing FA Licence case

---

web/static/web/css/pdfs/certificate-style.css
web/static/web/css/pdfs/com-certificate-style.css

ICMSLST-2485
Increasing QR code size in certificates

ICMSLST-2485 - Increasing QR code size

---

web/domains/case/urls.py
web/domains/case/views/views_pdf.py
web/tests/conftest.py
web/tests/domains/case/views/test_views_pdf.py

ICMSLST-1436
Checking application status to protect against pre-sign PDFs being generated when they're not warranted

ICMSLST-1436 - PDF pre-sign/preview view protection

---

data_migration/management/commands/_base.py
data_migration/management/commands/export_from_v1.py
data_migration/management/commands/extract_v1_xml.py
data_migration/management/commands/import_v1_data.py
data_migration/tests/conftest.py
data_migration/tests/test_export.py
data_migration/tests/test_import.py

- Silence data migration in non prod environments
- Remove need for environment to be production to run data migration

ICMSLST-2522 Data Migration - Silence data migration logs in non prod

---

web/templates/web/cookie-consent.html
web/views/forms.py

Changes:
- Add form to it's own row
- Render as p to fix style issue
- Set default cookie choice to No.

Fix form rendering.

---

.circleci/config.yml

Noticed this: 
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

Upgrade to latest stable ubuntu 2204 image.

---

pii-ner-exclude.txt
scripts/reset-local-docker-db
web/management/commands/add_reports_data.py
web/management/commands/utils/load_data.py
web/reports/forms.py
web/reports/interfaces.py
web/templates/web/domains/reports/run-report.html
web/tests/conftest.py
web/tests/reports/test_report_interfaces.py
web/tests/reports/test_views.py

Added multi-select legislation filter to Issued Certificates report

ICMSLST-2463 - Issued Certificates Legislation filter

---

pii-ner-exclude.txt
web/domains/case/_import/fa_dfl/forms.py
web/domains/case/_import/fa_oil/forms.py
web/domains/case/_import/fa_sil/forms.py
web/forms/fields.py
web/static/web/js/fox/core-footer.js
web/tests/domains/case/test_jquery_date_field.py

ICMSLST-1349 - SupplementaryReportForm Restrict year range for Date Received to 6 years

---

web/templates/web/domains/case/import/fa/provide-report/report-info.html

ICMSLST-1350 - Firearms Report - Correct guidance if not reporting any details.

---

requirements-playwright.txt
scripts/initial-setup.sh
web/end_to_end/case/export_app/test_create_cfs_application.py
web/end_to_end/case/export_app/test_create_com_application.py
web/end_to_end/case/export_app/test_create_gmp_application.py
web/end_to_end/case/import_app/test_create_fa_dfl_application.py
web/end_to_end/case/import_app/test_create_fa_oil_application.py
web/end_to_end/case/import_app/test_create_fa_sil_application.py
web/end_to_end/case/import_app/test_create_sanctions_application.py

ICMSLST-2545 Fix end to end tests.

---

pii-ner-exclude.txt
web/templates/web/domains/case/import/fa/partials/report-firearm-list.html

ICMLST-1353 - SIL Firearms Report - Correct guidance on how to provide the report details.

---

pii-ner-exclude.txt
web/templates/web/domains/case/import/fa/provide-report/buttons.html

ICMSLST-1351 - Firearms Report - Amend label for enter details manually button.

---

Makefile
config/settings.py
pii-ner-exclude.txt

This fixes the following bug:
CommandError: An error occurred during rendering 
/code/web/templates/base.html: Missing connections string

ICMSLST-2551 Add cache for django-compressor to use at build time.

---

config/env.py
config/settings.py
config/settings_test.py

Changes:
- Remove unused settings
- Remove unused environment variables from env.py
- Fix cookie views test that used real setting.

Remove unused Google Tag Manager settings.

---

pii-ner-exclude.txt
web/domains/firearms/views.py
web/domains/importer/views.py
web/domains/section5/views.py
web/domains/template/views.py

- Display a confirmation message after an Obsolete Calibre Group has been created successfully.
- Display a confirmation message after an Obsolete Calibre item has been created successfully.
- Display a confirmation message after a Sanction 5 Clause has been created successfully.
- Display a confirmation message after a CFS Declaration Translation item has been created successfully.
- Display a confirmation message after a CFS Schedule Translation item has been created successfully.
- Display a confirmation message after an Endorsement has been created successfully.
- Display a confirmation message after an Importer’s Firearms Authority has been created successfully.
- Display a confirmation message after an Importer’s Section 5 Authority has been created successfully.

ICMSLST-1606 - Adding confirmation messages on object(s) creation

---

web/tests/views/test_cookie_views.py
web/views/views.py

Setting only 1 key value in the cookie dictionary to avoid unnecessary escaping

ICMSLST-2524 - Google Analytics fixes

---

pii-ner-exclude.txt
web/domains/case/export/utils.py
web/domains/case/export/views.py
web/domains/case/services/document_pack.py
web/domains/case/urls.py
web/domains/case/views/views_search.py
web/templates/web/domains/case/export/copy-application.html
web/tests/conftest.py
web/tests/domains/case/export/test_utils.py
web/tests/domains/case/views/test_views_search.py
web/tests/helpers.py
web/tests/utils/search/test_search_actions.py
web/utils/search/actions.py

Changes:
- Implement Copy Application search action.
- Add CopyExportApplicationView.
- Add copy_export_application utility function.
- Add tests for new view / utility code.
- Remove Copy [Application / Template] actions for in progress applications.
New UI shown when pressing "Copy Application" in Export Application Search view.:

ICMSLST-1002 Add Copy Export Application View.

---

pii-ner-exclude.txt
web/domains/cat/views.py
web/end_to_end/case/import_app/test_create_fa_dfl_application.py
web/end_to_end/case/import_app/test_create_fa_oil_application.py
web/end_to_end/case/import_app/test_create_fa_sil_application.py
web/end_to_end/case/import_app/test_create_sanctions_application.py
web/end_to_end/cat/test_create_cfs_cat.py
web/end_to_end/cat/test_create_com_cat.py
web/end_to_end/cat/test_create_gmp_cat.py
web/end_to_end/conftest.py
web/end_to_end/search/test_revoke_fa_dfl_application.py
web/end_to_end/utils.py
web/templates/web/domains/cat/partials/table.html
web/tests/domains/cat/test_views.py

Changes:
- Add end to end test for CFS template.
- Add end to end test for GMP template.
- Add end to end test for COM template
- Add bypass_chief function to handle flaky task execution time.
- Update Create CAT view to redirect to Edit CAT view.

ICMSLST-2544 Add Certificate Application Template tests.

---

pii-ner-exclude.txt
requirements-base.txt
web/reports/interfaces.py
web/reports/serializers.py
web/reports/utils.py
web/reports/views.py
web/templates/web/domains/reports/run-output-view.html
web/tests/reports/test_utils.py
web/tests/reports/test_views.py

Display Parameters used to generate report:

ICMSLST-2557 Serialization Alias refactor / Display Parameters

---

web/domains/constabulary/forms.py

ICMSLST-1301 - Constabularies - Add 'Any' as default search option for Constabulary Region.

---

pii-ner-exclude.txt
web/domains/cat/utils.py
web/domains/cat/views.py

There is a related story to create a template from an application:
https://uktrade.atlassian.net/browse/ICMSLST-1241
When I get to that one I intend to refactor any common code.
```
Copy template to app: cat_utils.py -> set_template_data 
Copy app to app: export/utils.py -> copy_export_application
Copy app to template: ??? new code / refactored code from above.
```

ICMSLST-2583 Set CFS product data when creating an app from a template.

---

web/domains/firearms/forms.py
web/domains/firearms/views.py

ICMSLST-1317 - Obsolete Calibres - Label for Group Name needs correcting.

---

web/static/web/css/fox.css
web/templates/web/domains/firearms/group/edit.html
web/templates/web/domains/firearms/group/view.html

ICMSLST-1318 - Obsolete Calibres - Display hint messages when Group has no calibres attached.

---

web/templates/web/domains/section5/create.html

ICMSLST-1319 - Section 5 Clauses - Redundant sub-heading when creating Clause.

---

web/domains/legislation/forms.py
web/tests/domains/legislation/test_forms.py

ICMSLST-1321 - Product Legislation - Add 'Any' as default search option for filter fields.

---

web/domains/constabulary/views.py
web/domains/legislation/views.py
web/domains/sanction_email/views.py
web/domains/section5/views.py
web/domains/template/views.py
web/tests/domains/constabulary/test_views.py
web/tests/domains/section5/test_views.py
web/tests/domains/template/test_views.py
web/views/actions.py

Only active/current records can be edited for the following:
- Constabularies
- Sanction Emails
- Product Legislation
- Section 5 Clauses
- Templates

ICMSLST-1316 - Various ref data - No Edit option on archived records.

---

pii-ner-exclude.txt
web/domains/case/_import/fa_sil/forms.py
web/domains/case/_import/fa_sil/models.py
web/domains/case/_import/fa_sil/types.py
web/domains/case/_import/fa_sil/urls.py
web/domains/case/_import/fa_sil/utils.py
web/domains/case/_import/fa_sil/views.py
web/templates/web/domains/case/import/fa/partials/report-firearm-list.html
web/templates/web/domains/case/import/fa/provide-report/buttons.html
web/tests/conftest.py
web/tests/domains/case/_import/fa_sil/test_utils.py
web/tests/domains/case/_import/fa_sil/test_views.py
web/tests/helpers.py

ICMSLST-1354 - SIIL Firearms Report - Include missing Upload Document option.

---

pii-ner-exclude.txt
web/domains/template/forms.py
web/domains/template/views.py
web/tests/domains/template/test_forms.py
web/tests/domains/template/test_views.py

Also changed the Template name field on the TemplateFilter to search on both template_name and template_title.
Before:
After:

ICMSLST-1323 - Templates - Add 'Any' as default search option and other corrections.

---

web/static/web/css/fox.css
web/templates/display/fields.html
web/templates/web/domains/case/export/partials/cfs/edit-manufactured-at.html

ICMSLST-1567 - CFS - correctly display Manufacturer's address.

---

web/templates/web/domains/case/export/partials/cfs/edit-schedule-form-content.html

Most of the work already done, simply adding the tooltip.
Before:
After:

ICMSLST-1291 - CFS - Include responsible person statement if Cosmetic legislation selected.

---

pii-ner-exclude.txt
web/domains/case/export/forms.py
web/tests/domains/case/export/test_forms.py

ICMSLST-1280 - CoM - Application - convert Y/N questions to radio buttons.

---

web/domains/case/export/forms.py

ICMSLST-1292 - CFS/CoM - Prevent selection of more menu items than the maximum permitted.

---

.pre-commit-config.yaml
requirements-base.txt
requirements-dev.txt

https://cwe.mitre.org/data/definitions/444.html
https://github.com/uktrade/icms/security/dependabot/32

Upgrade gunicorn to fix CWE-444.

---

web/domains/case/export/models/cfs_models.py
web/domains/case/export/models/gmp_models.py
web/migrations/0001_initial.py

ICMSLST-1604 - Any application - amend find address to use Search as default.

---

web/domains/exporter/forms.py
web/domains/importer/forms.py
web/domains/importer/views.py

Changes:
- Fix duplicate importers in results.
- Fix duplicate exporters in results.
- Fix inactive importers being included in results.
- Fix inactive exporters being included in resusts.
Screenshot from before change highlighting two problems (duplicate records and inactive agents affecting the results)
Screenshot after fixing both bugs:

ICMSLST-2093 Fix several filtering bugs relating to agents.

---

pii-ner-exclude.txt
web/domains/case/views/views_email.py
web/templates/web/domains/case/manage/case-email-box.html
web/tests/domains/case/views/test_views_email.py

ICMSLST-1584 - Manage Case - make response box automatically available once email sent.

---

pii-ner-exclude.txt
requirements-playwright.txt
web/domains/case/_import/derogations/views.py
web/domains/case/_import/fa_dfl/urls.py
web/domains/case/_import/fa_dfl/views.py
web/domains/case/_import/fa_oil/views.py
web/domains/case/_import/fa_sil/utils.py
web/domains/case/_import/ironsteel/views.py
web/domains/case/_import/opt/views.py
web/domains/case/_import/sanctions/views.py
web/domains/case/_import/sps/views.py
web/domains/case/_import/textiles/views.py
web/domains/case/_import/wood/views.py
web/domains/case/export/views.py
web/domains/case/services/case_progress.py
web/domains/case/views/views_prepare_response.py
web/domains/chief/serializers.py
web/end_to_end/case/import_app/test_create_fa_dfl_application.py
web/end_to_end/case/import_app/test_create_fa_oil_application.py
web/end_to_end/case/import_app/test_create_fa_sil_application.py
web/end_to_end/utils.py
web/templates/partial/case/sidebar.html
web/templates/web/domains/case/import/fa-dfl/edit.html
web/templates/web/domains/case/import/fa-dfl/goods-list.html
web/tests/domains/case/_import/fa_dfl/test_views.py
web/tests/domains/case/_import/fa_sil/test_views.py
web/tests/domains/case/_import/sanctions/test_views.py
web/utils/pdf/utils.py

Changes:
- Add DFLGoodsCertificateDetailView class.
- Add InProgressApplicationStatusTaskMixin class.
- Fix several places showing deleted goods certificate files.
- ICMSLST-1484 Fix all page URL labels on Summary view.
- Fix end to end tests broken in ICMSLST-1412.
- Remove unnecessary end to end test dependencies.

ICMSLST-2459 Add Goods Certificates view to display fa-dfl goods.

---

pii-ner-exclude.txt
web/domains/case/_import/sanctions/forms.py
web/domains/case/_import/sanctions/urls.py
web/domains/case/_import/sanctions/views.py
web/end_to_end/case/import_app/test_create_sanctions_application.py
web/templates/partial/case/sidebar.html
web/templates/web/domains/case/import/sanctions/edit_application.html
web/templates/web/domains/case/import/sanctions/goods-list.html
web/templates/web/domains/case/import/sanctions/supporting-documents-list.html
web/tests/domains/case/_import/sanctions/test_forms.py
web/tests/domains/case/_import/sanctions/test_views.py

Changes:
- Add Goods view to display Sanctions goods.
- Add Supporting Documents view to display Sanctions documents.
Before:
After:

ICMSLST-2461 Add views to display sanctions goods and supporting documents.

---

web/domains/case/fir/forms.py
web/domains/case/views/utils.py
web/domains/case/views/views_fir.py
web/domains/case/views/views_misc.py
web/static/web/js/pages/edit-fir-access-request.js
web/static/web/js/pages/edit-fir.js
web/templates/partial/case/edit-fir.html
web/templates/web/domains/case/manage/edit-fir.html
web/tests/domains/case/fir/test_forms.py
web/tests/domains/case/views/test_views_fir.py

ICMSLST-1822 - All applications - Further Information request the from ILB cases prompts decision action to release ownership

---

pii-ner-exclude.txt
web/domains/case/export/forms.py

ICMSLST-2648 - In the export COM application a user is allowed to select and save more than 40 countries

---

pii-ner-exclude.txt
web/templates/web/domains/workbasket/workbasket.html

ICMSLST-2668 Add search links to help ILB caseworkers filter applications.

---

data_migration/management/commands/config/data_counts.py
data_migration/queries/export_application/cat.py
data_migration/queries/export_application/data_counts.py
data_migration/tests/utils/xml_data/cat.py
data_migration/utils/xml_parser/cat.py

- Fix the cat countries xml parser as COUNTRIES is the root node, not COUNTRY_LIST
- Add post migration checks to check that cat countries have been migrated

ICMSLST-2619 Data Migration - CAT Countries Fix and Checks

---

pii-ner-exclude.txt
web/templates/partial/case/export/sidebar-management.html
web/tests/domains/case/views/test_views_email.py

ICMSLST-2552 - Open / Total Email Counts on BEIS / HSE emails

---

.env.circleci
.env.local-docker
config/env.py
config/settings.py
web/auth/utils.py
web/one_login/tests/test_views.py
web/one_login/utils.py

Logs showing correct code paths:
Importer Login:
Exporter Login:

ICMSLST-2646 Support multiple One Login clients.

---

pii-ner-exclude.txt
web/domains/case/views/views_email.py
web/static/web/css/fox.css
web/templates/web/domains/case/manage/case-emails.html
web/tests/conftest.py
web/tests/domains/case/views/test_views_email.py

ICMSLST-2549 - Constabulary Emails - Expired Authorities Warning

---

pii-ner-exclude.txt
web/domains/case/export/models/common_models.py
web/domains/case/models.py
web/domains/case/urls.py
web/domains/case/views/views_misc.py
web/static/web/js/components/dialogues.js
web/templates/web/domains/case/manage/base.html
web/tests/conftest.py
web/tests/domains/case/test_tasks.py
web/tests/domains/case/views/test_views_misc.py
web/tests/helpers.py
web/tests/utils/pdf/test_signer.py

Quick-issue button to automatically approve and authorise documents for an accepted application.
Not approved:
Approved:

ICMSLST-2403 - Re-instate the Quick Issue button

---

.env.circleci
.env.local-docker
config/celery.py
config/cf_env.py
config/settings.py
config/wsgi.py
pii-ner-exclude.txt

Changes:
- Move CloudFoundryEnvironment to cf_env.py
- Remove common EnvironmentBase class so each env can diverge.
- Add env_prefix to DBTPlatformEnvironment class.
- Refactor all env files to set ICMS_ prefix.
- Fix incorrect default DJANGO_SETTINGS_MODULE value.

ICMSLST-2628 Refactor env vars to work with copilot secret init.

---

pii-ner-exclude.txt
web/domains/exporter/views.py
web/domains/importer/views.py
web/domains/sanction_email/views.py
web/tests/domains/exporter/test_views.py
web/tests/domains/importer/test_views.py
web/tests/domains/sanction_emails/test_views.py
web/tests/helpers.py

Updated admin screens
- Sanction Emails
- Importer
- Exporter
Updated redirect and added django message popup

ICMSLST-2670 - Admin view redirects

---

web/templates/partial/case/save-info-box.html
web/templates/web/domains/case/export/add_supporting_document.html
web/templates/web/domains/case/export/cfs-edit-schedule.html
web/templates/web/domains/case/export/cfs-edit.html
web/templates/web/domains/case/export/cfs-manufacturer-address.html
web/templates/web/domains/case/export/gmp-edit.html
web/templates/web/domains/case/export/gmp-view.html
web/templates/web/domains/case/export/prepare-com.html
web/templates/web/domains/case/import/fa-dfl/add_goods_certificate.html
web/templates/web/domains/case/import/fa-dfl/edit.html
web/templates/web/domains/case/import/fa-dfl/goods-list.html
web/templates/web/domains/case/import/fa-oil/edit.html
web/templates/web/domains/case/import/fa-sil/edit.html
web/templates/web/domains/case/import/fa-sil/goods/list.html
web/templates/web/domains/case/import/fa/certificates/create.html
web/templates/web/domains/case/import/fa/certificates/manage.html
web/templates/web/domains/case/import/fa/import-contacts/create.html
web/templates/web/domains/case/import/fa/import-contacts/list.html
web/templates/web/domains/case/import/sanctions/add_document.html
web/templates/web/domains/case/import/sanctions/add_or_edit_goods.html
web/templates/web/domains/case/import/sanctions/edit_application.html
web/templates/web/domains/case/import/sanctions/goods-list.html
web/templates/web/domains/case/import/sanctions/supporting-documents-list.html
web/templates/web/domains/case/import/wood/add_contract_document.html
web/templates/web/domains/case/import/wood/add_supporting_document.html
web/templates/web/domains/case/import/wood/edit.html
web/templates/web/domains/case/import/wood/edit_contract_document.html

ICMSLST-2667 - Display User Guidance text

---

web/domains/country/views.py
web/domains/firearms/views.py
web/domains/mailshot/views.py
web/views/mixins.py

Update PostActionMixin class to only allow execution of methods defined in post_actions.

ICMSLST-1235 Improve PostActionMixin security.

---

pii-ner-exclude.txt
web/end_to_end/case/export_app/test_create_cfs_application.py
web/end_to_end/case/export_app/test_create_com_application.py
web/end_to_end/case/export_app/test_create_gmp_application.py
web/end_to_end/case/import_app/test_create_fa_dfl_application.py
web/end_to_end/case/import_app/test_create_fa_oil_application.py
web/end_to_end/case/import_app/test_create_fa_sil_application.py
web/end_to_end/case/import_app/test_create_sanctions_application.py
web/end_to_end/cat/test_create_cfs_cat.py
web/end_to_end/cat/test_create_com_cat.py
web/end_to_end/cat/test_create_gmp_cat.py
web/management/commands/add_dummy_data.py

Changes:
- ICMSLST-2717: Fix add_ilb_admin_users in add_dummy_data.py
- ICMSLST-2717: Update organisation labels in e2e tests.
- ICMSLST-2666: Update Sanctions form labels in e2e tests.

Several end to end test fixes.

---

web/templates/web/domains/case/export/partials/process.html
web/templates/web/domains/case/import/partials/process.html

Import application view:
Export application view:

ICMSLST-2696 Show organisation address and postcode for all app types.

---

web/domains/case/views/views_update_request.py
web/templates/partial/case/sidebar.html
web/tests/domains/case/views/test_views_update_request.py

Changes:
- Move "Application Updates" link above "Submit" link.
- Update confirm changes redirect link to application submit view.
New link location:
After clicking submit:

ICMSLST-2698 Application Update UI changes.

---

web/domains/case/access/views.py
web/templates/web/domains/case/access/management.html

ICMSLST-2702 Show message after linking an org to an access request.

---

web/domains/case/access/views.py
web/templates/web/domains/case/access/management.html

ICMSLST-2704 Add help text for creating a new org via access requests.

---

pii-ner-exclude.txt
web/domains/workbasket/actions/ilb_admin_actions.py
web/domains/workbasket/row.py
web/tests/domains/workbasket/actions/test_ilb_admin_actions.py

Application Processing section label is used in several actions. This fix ensures the label is consistent in every place it is used.
Changes:
- Call get_app_processing_label in several workbasket actions.
- Remove invalid logic in ViewApplicationCaseAction.
- Refactor get_workbasket_row_func.

ICMSLST-2716 Fix Application Processing workbasket section label.

---

web/domains/case/services/case_progress.py
web/domains/case/views/views_update_request.py
web/domains/workbasket/actions/applicant_actions.py
web/tests/domains/case/services/test_case_progress.py

Changes:
- Show FIR and Update requests to applicants when there is no case owner.
- Update application_in_progress to check for update request edge case.

ICMSLST-2729 Fix Update Request and FIR not appearing in workbasket.

---

web/domains/case/views/views_update_request.py
web/mail/emails.py

Changes:
- Fix Application Update response email send to list.
- Fix Variation Request update response email send to list.
- Add todo comment for ICMSLST-2737.

ICMSLST-2736 Fix two places optional case owner used to send emails.

---

web/domains/case/access/forms.py

Agent link is optional to allow approval step:
Form checks for agent when closing access request:

ICMSLST-2703 Access Request form changes based on ILB feedback.

---

pii-ner-exclude.txt
web/templates/web/domains/case/import/sanctions/add_document.html
web/templates/web/domains/case/import/sanctions/supporting-documents-list.html

ICMSLST-2726 Update info box on sanction document views.

---

web/templates/web/domains/case/export/cfs-edit-schedule.html

ICMSLST-2732 Add a Add Schedule button to the edit schedule view.

---

web/templates/partial/importer/detail.html

ICMSLST-2723 Fix comments field on View Importer page.

---

.pre-commit-config.yaml
Makefile
config/settings.py
pii-ner-exclude.txt
web/domains/case/export/models/common_models.py
web/domains/case/forms_search.py
web/domains/case/models.py
web/domains/case/services/case_progress.py
web/domains/case/views/views_misc.py
web/domains/case/views/views_pdf.py
web/domains/workbasket/app_data.py
web/jinja2.py
web/mail/emails.py
web/management/commands/utils/add_template_data.py
web/models/mixins.py
web/one_login/utils.py
web/static/web/css/fox_default_layout.css
web/templates/display/fields.html
web/tests/utils/pdf/test_generator.py
web/tests/utils/search/test_search.py
web/tests/utils/test_lock_manager.py
web/utils/currency.py
web/utils/pdf/generator.py
web/views/actions.py

Changes:
- Remove references to done tickets.
- Add missing ticket numbers.
- Refactor all comments to use same format: # TODO: ICMSLST-XXX

Revisit all todo comments.

---

pii-ner-exclude.txt
pii-secret-exclude.txt
web/static/web/css/fox_default_layout.css
web/templates/base.html
web/templates/layout/public.html
web/templates/web/accessibility_statement.html
web/urls.py
web/views/__init__.py
web/views/views.py

ICMSLST-2685 - Accessibility Statement

---

web/templates/web/domains/mailshot/partials/detail.html

Bugfix in mailshot detail view, sent to checkboxes are always checked

ICMSLST-2719 Fix view mailshot detail sent to check boxes

---

.env.circleci
.env.local-docker
pii-ner-exclude.txt
web/domains/case/access/approval/models.py
web/domains/workbasket/app_data.py
web/domains/workbasket/base.py
web/domains/workbasket/row.py
web/management/commands/add_test_data.py
web/tests/conftest.py
web/tests/domains/workbasket/test_views.py

Changes: 
- Show approved status of access approval request in ILB workbasket
- Add missing workbasket tests for access & approval requests

ICMSLST-2752 Show approved status of access request in ILB workbasket.

---

web/management/commands/add_dummy_data.py

Changes:
- Add dummy verified firearms authority to importer records.
- Add dummy verified section 5 authority to importer records.
Each dummy importer now has a valid authority for each section:
This ensures a valid selection can be chosen when creating firearms applications:

ICMSLST-2768 Add Dummy Verified and Section 5 firearms authorities

---

config/settings.py
pii-ner-exclude.txt
web/static/web/js/components/show-hide-modal-event-handler.js
web/templates/web/company_list.html
web/templates/web/domains/case/import/fa/provide-report/report-info.html
web/templates/web/domains/country/translations/edit.html
web/templates/web/domains/country/translations/list.html

Removing HTTPS:// and www. from the directives to make them more accepting
Removing all onclick handlers

General CSP fixes

---

.pre-commit-config.yaml
requirements-base.txt

Upgrading Sentry

---

web/templates/login_start.html
web/views/views.py

Import a licence start page:
Export a certificate start page:
Caseworker start page:

ICMSLST-2781 Update Login Start content on importer / exporter sites.

---

pii-ner-exclude.txt
web/templates/web/domains/case/access/partials/access-request-section.html
web/templates/web/domains/case/access/request-importer-access.html

Importer user viewing an access request
Exporter user viewing an access request
ILB Admin user viewing an importer & exporter access request

ICMSLST-2776 Add missing optional fields when viewing access requests.

---

web/templates/web/domains/user/one_login/user_edit.html

ICMSLST-2780 Update new user edit view content.

---

web/static/web/css/pdfs/constants.css
web/static/web/css/pdfs/sanctions-licence-style.css
web/templates/pdf/import/sanctions-licence.html
web/utils/pdf/generator.py
web/utils/pdf/pages.py

Also included the feedback from the doc here - https://dbis.sharepoint.com/:w:/r/sites/dit253/_layouts/15/Doc.aspx?sourcedoc=%7B5C06AA06-06EB-4EDB-A659-4899C1F3720C%7D&amp=&file=Sanctions%20and%20Adhoc%20PDF%20Formatting%20Issues.docx&action=default&mobileredirect=true&wdsle=0

ICMSLST-2858 - Sanctions licence PDF -> Styling bugs

---

web/domains/chief/serializers.py
web/tests/domains/chief/test_serializers.py

The limit for restrictions in CHIEF is 2000 characters. ICMS V1 truncates after 950 characters so this change allows more than double the characters V1 sends to CHIEF.

ICMSLST-2855 Truncate endorsement text sent to icms-hmrc.

---

web/domains/chief/client.py
web/tests/domains/chief/test_client.py

ICMSLST-2855 Store the error from ICMS-HMRC to show on CHIEF Dashboard.

---

web/templates/web/domains/case/authorisation.html

ICMSLST-2851 - Authorisation -> info-box message no longer correct.

---

pii-ner-exclude.txt
web/domains/case/services/case_progress.py
web/domains/case/views/mixins.py
web/flow/errors.py
web/templates/403_view_no_longer_available.html
web/tests/domains/case/services/test_case_progress.py
web/tests/domains/case/views/test_views_pdf.py
web/tests/views/test_views.py
web/views/views.py

ICMSLST-2846 Add better error handling when a user presses back button.

---

web/templates/web/v1_user_bookmark_info.html
web/views/views.py

ICMSLST-2910 V1ToV2ServiceRenameView content changes.

---

.circleci/config.yml
web/templates/web/domains/case/authorisation.html

ICMSLST-2852 - Authorisation -> Missing confirmation popup

---

web/admin.py

If an existing group is removed:
If a new group is added:

ICMSLST-2912 Add user group form validation to admin site.

---

config/settings.py
pii-ner-exclude.txt
web/domains/case/context_processors.py
web/templates/layout/sidebar.html
web/templates/web/domains/case/export/cfs-view.html
web/templates/web/domains/case/export/com/view.html
web/templates/web/domains/case/export/gmp-view.html
web/templates/web/domains/case/export/partials/process.html
web/templates/web/domains/case/import/derogations/view.html
web/templates/web/domains/case/import/fa-dfl/view.html
web/templates/web/domains/case/import/fa-oil/view.html
web/templates/web/domains/case/import/fa-sil/view.html
web/templates/web/domains/case/import/ironsteel/view.html
web/templates/web/domains/case/import/opt/view.html
web/templates/web/domains/case/import/partials/process.html
web/templates/web/domains/case/import/sanctions/view.html
web/templates/web/domains/case/import/sps/view.html
web/templates/web/domains/case/import/textiles/view.html
web/templates/web/domains/case/import/wood/view.html
web/templates/web/domains/case/view_case.html

Changes:
- Update import app case banner.
- Update export app case banner.
- Add Importer & Exporter sections to view application view.
**View Import application before:**
**View Import application after:**
**View Export application before:**
**View Export application after:**

ICMSLST-2833 Case banner and view app UI changes.

---

pii-ner-exclude.txt
web/domains/case/_import/fa/views.py
web/templates/partial/certificates/list-verified.html
web/templates/web/domains/case/import/fa/certificates/view-verified.html

Changes:
- Always show "Show Details" link.
- Fix View Verified Firearms Authority UI.
- Fix certificates shown when creating an FA-OIL application.
**When View Details is clicked the following page appears in a new tab:**

ICMSLST-2945 Fix view verified firearms authority link.

---

web/templates/web/domains/case/import/create.html

**FA-DFL & FA-SIL:**
**FA-OIL:**
**All other import applications:**

ICMSLST-2862 Add domestic authority warning to firearms applications.

---

web/domains/workbasket/row.py
web/templates/web/domains/workbasket/workbasket.html
web/tests/domains/workbasket/test_views.py

ICMSLST-2845 Fix access request workbasket action labels.

---

Makefile

Changes:
- Remove UID variable.
- Remove unused commands.

ICMSLST-2762 Remove UID variable from makefile.

---

pii-ner-exclude.txt
web/templates/web/domains/case/access/access-request-history.html

ICMSLST-2987 Show access request response and response reason.

---

web/templates/web/domains/case/access/partials/pending-requests.html

ICMSLST-2988 Add help text guiding users to account recovery.

---

web/domains/checker/forms.py

ICMSLST-1412 incorrectly updated this form field and required the user to be logged in.
Countries are now shown:

ICMSLST-2992 Fix certificate checker country picker.

---

web/templates/web/domains/case/manage/update-requests/edit.html
web/templates/web/domains/case/manage/update-requests/list.html
web/templates/web/domains/case/respond-update-request.html
web/templates/web/domains/case/start-update-request.html

Example of the change in one of the 999 templates that show update requests:

ICMSLST-2997 Add request_datetime to all update request templates.

---

web/domains/workbasket/row.py

ILB would only like to see the organisation name field for access requests in the workbasket.

ICMSLST-3011 Update access request workbasket row information.

---

pii-ner-exclude.txt
web/domains/case/access/filters.py
web/domains/case/access/views.py
web/tests/domains/case/access/test_views.py

ICMSLST-3012 - Search by Access Request Reference

---

web/domains/case/forms_search.py
web/templates/web/domains/case/search/search.html

ICMSLST-3016 Allow users to search for "." character.

---

web/domains/case/access/views.py

ICMSLST-3018 Fix access request list page ordering.

---

pii-ner-exclude.txt
web/domains/case/forms.py
web/templates/web/domains/case/manage/reassign-ownership.html

ICMSLST-2850 Fix release ownership UI.

---

web/domains/case/access/views.py
web/tests/domains/case/access/test_views.py

ICMSLST-2991 Set closed_datetime and closed_by when closing AR.

---

web/templates/web/domains/case/access/partials/access-request-list.html
web/templates/web/domains/case/access/request-exporter-access.html

ICMSLST-2871 Add FIRs to pending access requests.

---

web/templates/web/domains/case/respond-fir.html

ICMSLST-2842 Add missing message to respond to fir view.

---

web/domains/workbasket/row.py
web/tests/domains/workbasket/test_row.py

Value used is the submit datetime if set and defaults to created for in progress application.

ICMSLST-3020 Fix workbasket timestamp field.

---

web/templates/web/domains/case/export/cfs-view.html
web/templates/web/domains/case/import/fa-dfl/view.html

Before:
After:
Also applied the same disabled check box fix to CFS
Before:
After:

ICMSLST-2875 - FA-DFL UI Changes

---

pii-ner-exclude.txt
web/domains/case/_import/fa_sil/forms.py
web/templates/partial/certificates/list-verified.html
web/templates/partial/certificates/list.html
web/templates/partial/import-contacts/list.html
web/templates/partial/know-bought-from.html
web/templates/web/domains/case/import/fa-sil/view.html
web/templates/web/domains/case/import/fa/certificates/manage.html
web/templates/web/domains/case/import/fa/import-contacts/list.html
web/templates/web/domains/case/import/partials/fa-sil/user-section5-authorities.html

ICMSLST-2869 - FA-SIL UI Improvements

---

web/templates/web/domains/case/import/fa/provide-report/report-info.html

ECIL-230 - Missing header when supplementary report complete

---

web/templates/partial/case/export/sidebar-management.html
web/templates/partial/case/import/sidebar-management.html
web/templates/partial/update-request-detail.html

ECIL-232 Fix sidebar counts for app withdrawals, app updates and FIRs.

---

pii-ner-exclude.txt
web/domains/case/fir/forms.py
web/templates/partial/case/edit-fir.html
web/templates/partial/case/fir.html
web/templates/web/domains/case/respond-fir.html

Changes:
- Update several labels
- Align all buttons when editing a FIR.
- Only show response fields when set.
- Align submit response button with form field.
Screenshots:

ECIL-233 Fix several UI issues relating to FIRs

---

config/settings.py
web/ecil/template_backends/jinja2.py

All credit to @marcuspp for this one:
https://github.com/uktrade/icms/pull/1914

Fix compressor failing to find EcilJinja2Backend template backend.

---

pii-ner-exclude.txt
web/domains/template/widgets.py
web/tests/domains/template/test_views.py
web/tests/domains/template/test_widgets.py

- Fix lookup for endorsement template widget
- Add full test coverage for admin template views

ECIL-225 Test coverage for admin templates

---

pii-ner-exclude.txt
web/domains/case/views/views_view_case.py
web/templates/display/fields.html
web/templates/web/domains/case/export/com/view.html
web/templates/web/domains/case/export/gmp-view.html

Changes:
- Fix show_eu_fields optional datetime comparision
- Fix application_field macro rendering "None" instead of default.
- FIx all view export application templates from rendering "None".
View CFS before change:
View CFS after change:

ECIL-255 Fix view in progress CFS applications.

---

pii-ner-exclude.txt
web/ecil/gds/forms/fields.py
web/ecil/gds/forms/forms.py
web/tests/ecil/gds/forms/test_fields.py
web/tests/ecil/gds/forms/test_forms.py

Changes:
- Fix error summary link for GovUKDateInputField.
- Fix error summary link for GovUKCheckboxesField.
- Fix error summary link for GovUKRadioInputField.
- Add test for error_summary_kwargs.
- Rename GDSMixin to GDSFieldMixin.

ECIL-325 Fix error summary links for several form fields.

---

web/domains/case/export/views.py
web/domains/cat/views.py
web/templates/web/domains/cat/base_form.html

Banner on the edit CFS page
Banner on the edit schedule page when a CPTPP country and cosmetics legislation is selected

ECIL-424 Add CPTPP banners to CFS CAT

---

pii-ner-exclude.txt
web/domains/case/export/forms.py
web/domains/case/export/views.py
web/static/web/js/pages/cfs-edit.js
web/templates/web/domains/case/export/cfs-edit.html
web/templates/web/domains/case/export/partials/cfs/edit-schedule-form-content.html
web/tests/domains/case/export/test_forms.py
web/tests/reports/test_report_interfaces.py

The banner and the submission error message are now country specific

ECIL-427 Update CPTPP content only for selected countries

---

pii-ner-exclude.txt
web/templates/web/domains/case/manage/prepare-response.html

ECIL-219 Add warning in response prep for importers with no EORI

---

config/settings.py
requirements-dev.txt
requirements-prod.txt
requirements/requirements-base.in
web/tests/views/test_views.py
web/urls.py
web/views/views.py

Changes:
- Add OIDC back-channel logout view
- Add tests

ECIL-450 Add OIDC back-channel logout view.

---

web/domains/case/_import/urls.py
web/domains/case/_import/views.py
web/static/web/js/api/endorsement-text-lookup.js
web/static/web/js/pages/endorsement.js
web/templates/web/domains/case/import/manage/add-endorsement.html
web/tests/domains/case/_import/test_views.py

ECIL-227 Show endorsement content when adding endorsements.

---

web/domains/chief/serializers.py
web/domains/chief/types.py
web/domains/office/forms.py
web/forms/fields.py
web/management/commands/check_icms_hmrc_connection.py

This is a temporary change before adding more complex postcode logic. It should be conditionally optional depending on org type.

ECIL-486 Make postcode field optional.

---

web/admin.py
web/management/commands/create_icms_groups.py

Add readonly admin site page for UserFeedbackSurvey model.

---

pii-ner-exclude.txt
web/ecil/urls/urls.py
web/ecil/urls/urls_example.py
web/ecil/urls/urls_new_user.py
web/ecil/views/views_example.py
web/ecil/views/views_new_user.py
web/management/commands/add_test_data.py
web/menu/menu.py
web/templates/ecil/base.html
web/templates/ecil/new_user/exporter_login_start.html
web/tests/conftest.py
web/tests/domains/user/test_forms.py
web/tests/ecil/views/test_views_example.py
web/tests/ecil/views/test_views_new_user.py
web/urls.py

Changes:
- Add temporary menu item to see new views.
- Add exporter login start view.
- Refactor all ecil views to views_example.py
**New menu item:**
**New exporter start page:**

ECIL-572 Add exporter login start page.

---

pii-ner-exclude.txt
web/ecil/forms/forms_example.py
web/ecil/forms/forms_new_user.py
web/ecil/gds/forms/fields.py
web/ecil/gds/forms/forms.py
web/ecil/urls/urls_new_user.py
web/ecil/views/views_example.py
web/ecil/views/views_new_user.py
web/templates/ecil/new_user/update_name.html
web/tests/ecil/gds/forms/test_fields.py
web/tests/ecil/views/test_views_new_user.py

**Changes:**
- Add NewUserUpdateNameView view.
- Refactor how form fields create gds_kwargs.
- Allow Form and ModelForm fields to supply overrides.
- Refactor existing ecil forms to forms_example.py
**Screenshot:**

ECIL-178 Add NewUserUpdateNameView view.

---

web/templates/ecil/new_user/exporter_login_start.html

Add missing company details list item.

---

web/ecil/forms/forms_new_user.py
web/ecil/gds/forms/fields.py

ECIL-588 Add missing help text and classes to radio choices.

---

web/templates/ecil/access_request/exporter_countries-step.html

ECIL-580 Fix Add country button label.

---

web/domains/case/_import/forms.py
web/tests/domains/case/_import/test_views.py
web/tests/domains/case/views/test_views_prepare_response.py
web/tests/helpers.py

Edit licence view for variation requests:

ECIL-603 Fix licence start date checking logic for variation requests.

---

web/ecil/forms/forms_access_requests.py
web/ecil/gds/views/base.py
web/ecil/urls/urls_access_requests.py
web/ecil/views/views_access_requests.py
web/ecil/views/views_example.py
web/ecil/views/views_new_user.py
web/jinja2.py
web/templates/ecil/access_request/submitted_detail.html
web/tests/ecil/views/test_views_new_user.py

**Changes:**
- Add detail view shown after completing an access request.
- Fix bug in ExporterAccessRequestExportCountriesForm validation logic.
- Refactor MultiStepFormSummaryView to use self.new_object attribute.
- Add global ilb_contact_email jinja context variable.
**Screenshots:**

ECIL-582 Add access request submitted view.

---

pii-ner-exclude.txt
web/ecil/gds/component_serializers/error_summary.py
web/ecil/gds/component_serializers/panel.py
web/ecil/gds/component_serializers/summary_list.py
web/ecil/gds/component_serializers/table.py
web/ecil/gds/forms/forms.py
web/ecil/gds/views/base.py
web/ecil/views/views_access_requests.py
web/tests/ecil/gds/forms/test_forms.py
web/tests/ecil/views/test_views_example.py

Channges:
- Revisit all TODO comments where a serializer is needed
- Fix several optional serializer attributes.
- Remove old logic from export_countries_form_valid method.
- Add support for html summary display values.

ECIl-617 Refactor several gds macro kwargs to use serializers.

---

web/tests/ecil/views/test_views_access_requests.py

Changes:
- Add tests for ExporterAccessRequestTypeFormView.

ECIL-593 Add tests for ECIL exporter access request views.

---

web/domains/workbasket/app_data.py
web/ecil/forms/forms_example.py
web/tests/domains/workbasket/test_views.py

Changes:
- Only show approval requests to users with manage_contacts_and_agents permission
- Fix unrelated ExampleConditionalGDSModelForm conditional_fields.

ECIL-485 Fix approval request workbasket logic.

---

pii-ner-exclude.txt
web/domains/file/utils.py
web/domains/importer/views.py
web/domains/section5/forms.py
web/templates/web/domains/importer/create-section5-authority.html
web/templates/web/domains/importer/edit-section5-authority.html
web/tests/domains/importer/test_views.py

ECIL-504 - Ability to upload document the same time as creating a Section 5 Authority

---

web/domains/workbasket/actions/applicant_actions.py
web/tests/domains/workbasket/actions/test_applicant_actions.py

ECIL-634 Add EditECILApplicationAction to easily view CFS prototype.

---

pii-ner-exclude.txt
web/ecil/forms/forms_cfs.py
web/ecil/gds/component_serializers/radios.py
web/ecil/gds/forms/fields.py
web/ecil/urls/urls.py
web/ecil/urls/urls_cfs.py
web/ecil/urls/urls_export_application.py
web/ecil/views/views_access_requests.py
web/ecil/views/views_cfs.py
web/ecil/views/views_export_application.py
web/templates/ecil/export_application/another_contact.html
web/tests/ecil/views/test_views_cfs.py
web/tests/ecil/views/test_views_export_application.py
web/tests/reports/test_report_interfaces.py

**Changes:**
- Add CFSApplicationContactUpdateView.
- Add AnotherExportApplicationContactTemplateView.
- Fix several tests.
- Add missing types.
**Screenshots:**

ECIL-632 Add CFSApplicationContactUpdateView.

---

pii-ner-exclude.txt
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/ecil/views/views_export_application.py
web/templates/ecil/cfs/schedule_create.html
web/tests/ecil/views/test_views_cfs.py
web/tests/ecil/views/test_views_export_application.py

ECIL-646 Add create schedule view.

---

pii-ner-exclude.txt
web/domains/case/app_checks.py
web/domains/case/services/reference.py
web/domains/case/types.py
web/domains/case/views/views_email.py
web/domains/case/views/views_prepare_response.py
web/domains/chief/serializers.py
web/domains/template/context.py
web/management/commands/ECIL_652_add_nuclear_commodities.py
web/templates/partial/case/import/sidebar-management.html
web/templates/web/domains/case/import/manage/prepare-nuclear-material-response.html
web/tests/conftest.py
web/tests/domains/case/_import/nuclear_material/test_views.py

Screenshots:
- Response prep
- Case emails (still using sanctions template)
- ILB edit goods view

ECIL-649 Update caseworker views to work with NMIL application.

---

web/templates/pdf/import/nuclear-material-licence.html
web/utils/pdf/utils.py

ECIL-666 Changes to nuclear materials licence pdf

---

web/admin.py

Minor improvements to the list view

ECIL-692 Add user email and case ref to UserFeedbackSurveyAdmin

---

pii-ner-exclude.txt
web/templates/ecil/cfs/schedule_create.html

ECIL-705 ECIL CFS create schedule content changes.

---

pii-ner-exclude.txt
web/ecil/forms/forms_cfs.py
web/ecil/gds/forms/fields.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/tests/ecil/views/test_views_cfs.py

ECIL-707 Add CFSScheduleExporterStatusUpdateView view.

---

pii-ner-exclude.txt
web/ecil/forms/forms_cfs.py
web/ecil/gds/forms/fields.py
web/ecil/gds/forms/forms.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/tests/ecil/conftest.py
web/tests/ecil/views/test_views_cfs.py

Changes:
- Add CFSScheduleBrandNameHolderUpdateView view.
- Add choice_conditional_html kwarg to GovUKRadioInputField to support rendering conditional html for radio choice options.
- Refactor prototype_cfs_app_in_progress fixture.
- Add comment to help explain gds_radio_conditional_fields attribute.
Screenshots:
- ![export-a-certificate_8080_ecil_cfs_application_8_schedule_12_brand-name-holder_](https://github.com/user-attachments/assets/b050c045-9334-4f4e-b234-e18461441573)
- ![export-a-certificate_8080_ecil_cfs_application_8_schedule_12_brand-name-holder_ (1)](https://github.com/user-attachments/assets/bbb4bfce-e06e-47be-9321-b48a961d058c)

ECIL-709 Add CFSScheduleBrandNameHolderUpdateView view.

---

web/ecil/forms/forms_cfs.py
web/ecil/gds/forms/fields.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/templates/ecil/cfs/schedule_country_of_manufacture.html
web/tests/ecil/views/test_views_cfs.py

ECIL-710 Add CFSScheduleCountryOfManufactureUpdateView view.

---

web/ecil/forms/forms_cfs.py
web/ecil/gds/views/base.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/templates/ecil/cfs/help_text/schedule_exporter_status.html
web/templates/ecil/cfs/help_text/schedule_legislations.html
web/templates/ecil/cfs/help_text/schedule_remove_legislation.html
web/templates/ecil/cfs/schedule_legislation.html
web/templates/ecil/cfs/schedule_legislation_add_another.html
web/tests/ecil/views/test_views_cfs.py

**Changes:**
- Add CFSScheduleAddLegislationUpdateView view.
- Use render_to_string for several help_text's that render html.
- Add CFSScheduleAddAnotherLegislationFormView view.
- Add CFSScheduleConfirmRemoveLegislationFormView view.
- ECIL-638 Add _referrer_view session variable to BackLinkMixin.
**Screenshots:**
- Add legislation view

ECIL-711 Add CFS schedule legislation views.

---

web/ecil/forms/forms_export_application.py
web/ecil/urls/urls_export_application.py
web/ecil/views/views_cfs.py
web/ecil/views/views_export_application.py
web/templates/ecil/cfs/schedule_legislation_add_another.html
web/templates/ecil/export_application/export_countries.html
web/templates/ecil/export_application/export_country_add_another.html
web/tests/ecil/views/test_views_cfs.py
web/tests/ecil/views/test_views_export_application.py

ECIL-704 Update exporter country select views to work with latest design

---

web/templates/web/domains/case/import_licence_history.html

Changes:
- Add missing import used when displaying refused reason.

ECIL-750 Fix case history view not showing refused applications.

---

web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/templates/ecil/cfs/schedule_product_start.html
web/tests/ecil/views/test_views_cfs.py

Changes:
- Add CFSScheduleAddProductStartTemplateView view.
- Refactor several CFS views.
- Use BackLinkMixin in several views.
- Create several common base classes.
Screenshots:

ECIL-738 Add CFSScheduleAddProductStartTemplateView.

---

web/ecil/forms/forms_cfs.py
web/ecil/gds/views/base.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/tests/ecil/views/test_views_cfs.py

Changes:
- Add CFSScheduleAddProductMethodFormView view.
- Refactor CFSScheduleBaseFormView to set self.object attribute.
- Improve get_back_link_url not implemented error message.
Screenshots:

ECIL-739 Add CFSScheduleAddProductMethodFormView view.

---

web/ecil/forms/forms_cfs.py
web/ecil/urls/urls_cfs.py
web/ecil/views/views_cfs.py
web/templates/ecil/cfs/schedule_product_type_add_another.html
web/templates/gds/components/list-with-actions/macro.html
web/tests/ecil/views/test_views_cfs.py

Changes:
- Add CFSScheduleProductTypeCreateView view.
- Add CFSScheduleProductTypeAddAnotherFormView view.
- Add CFSScheduleProductTypeConfirmRemoveFormView view.
- fix list-with-actions macro spacing.
- Refactor several ecil cfs views.

ECIL-745 Add several product type number views.
