.gitignore, Makefile, README.md, docker-compose.yml
- auto remove containers started with `docker-compose run`
- data persistence for postgres container, otherwise data is lost every time containers are downed
- updates to readme file, explaining to run `make setup` before first run so we have db migrations in place
- added makefile `down` target to run `docker-compose down`
- added makefile `setup` target to run migrations and install dependencies, used as part of new dev onboarding
=> Improvements to project for first run

web/static/web/js/action-buttons.js, web/templates/partial/agents.html, web/templates/partial/firearms-authorities.html, web/templates/partial/offices.html, web/templates/partial/section5-authorities.html, web/templates/web/contacts/list.html, web/templates/web/portal/outbound-emails.html
* replaced FOXjs.actions with action button on several template files
* action buttons support the notion of `standalone buttons` (eg: to use as actions in list views) and `in form action buttons` (to use in conjunction with exiting forms, eg: a delete button that needs to pass existing data)
=> replace FOXjs.actions with action button

Makefile, config/settings/test.py
Details:
* Use faster password hashing algo for tests.
* Run unittests in parallel (fixed at 4 for now).
Timings:
unittests:
Before: 2m10s
With faster password hashing: 0m50s
With faster password hashing and 4x parallel: 0m27s
BDD tests:
Before: 3m6s
With faster password hashing: 2m56s
=> ICMSLST-405 Speed up tests.

web/domains/importer/forms.py, web/domains/importer/views.py
Prefetch `offices` as they are displayed in every row of the `importer-list` view. Prefetching offices avoid to issue a query every time an office should be displayed (see https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.prefetch_related). The prefetch reduces the queries from 53 (1 office for each row) to 4.
Fix `select_related` which was targeting the wrong model. It was `user` and it target `main_importer`.
=> Reduce query number on importer

web/templates/web/domains/importer/search-companies.html
When querying companies house company number is returned as
`company_number`.
The bug is avoiding company number to be displayed when associating an
organisation with a company.
=> Fix typo json returns `company_number` not `companyNumber`

runtime.txt
See https://docs.cloudfoundry.org/buildpacks/python/index.html#runtime
To request the latest Python version in a patch line, replace the patch version
with x: 3.6.x. To request the latest version in a minor line, replace the minor
version: 3.x.
=> Use latest python (3.7.x) for cloudfoundry

requirements-base.txt
Attempt to fix the following error:
```
RuntimeWarning: greenlet.greenlet size changed, may indicate binaryincompatibility. Expected 144 from C header, got 152 from PyObject
```
=> Update gevent to 20.9.0

web/domains/section5/forms.py, web/static/web/css/fox.css, web/tests/domains/importer/test_views.py
When calling `commit=False` on `form.save`, it needs to call manually
`form.save_m2m()`.
see
https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/#the-save-method
> To work around this problem, every time you save a form using commit=False,
> Django adds a save_m2m() method to your ModelForm subclass. After you’ve
> manually saved the instance produced by the form, you can invoke save_m2m()
> to save the many-to-many form data.
=> ICMSLST-468 Fix linked offices not being saved

web/domains/template/views.py, web/templates/web/domains/template/edit-cfs-schedule-translation.html
Note that this is not for the translations themselves, just for the
template-level data (name, countries, etc). It does show the translations
and contains a link to edit them (upcoming ticket).
Looks like this:
=> ICMSLST-86 Add edit screen for "CFS Schedule translation".

docker-compose.yml
This brings back the localstack web UI, among other things.
=> ICMSLST-590 Pin down external docker images in docker-compose.yml.

web/domains/case/_import/derogations/views.py, web/domains/case/_import/firearms/views.py, web/domains/case/_import/sanctions/views.py, web/domains/case/_import/views.py
- Add default endorsements to Derogations;
- Set licence_start_date when case is taken by ILB Admin.
And add tickets to use endorsement usages instead of endorsements.
Endorsement usages are managed by ILB Admins. They allow to link an
application type with endorsements. Which in turn are used to generate
the licence.
=> Icmslst 486 add endorsements licence dates

web/domains/firearms/forms.py, web/domains/firearms/views.py, web/domains/importer/urls.py, web/templates/partial/firearms-authorities.html, web/templates/partial/firearms-authorities/list.html, web/templates/web/domains/case/import/firearms/manage-constabulary-emails.html, web/templates/web/domains/importer/add-document-firearms.html, web/templates/web/domains/importer/detail-firearms-authority.html, web/templates/web/domains/importer/detail-section5-authority.html, web/templates/web/domains/importer/edit-firearms-authority.html, web/tests/domains/firearms/test_views.py
Also add viewing uploaded documents.
Also clean up importer/firearms authority code.
In more detail:
* Remove unnecessary importer_pk from various URLs.
* Shorten URLs / view names / function names by removing "[-_]_authorities".
=> ICMSLST-636 Use single-file uploads for importer/firearms.

web/domains/case/_import/forms.py, web/domains/case/_import/models.py, web/domains/case/_import/views.py, web/domains/case/forms.py, web/domains/case/models.py, web/migrations/0020_withdrawimportapplication.py, web/templates/web/domains/workbasket/partials/import-case.html
The postgres-level DB constraints created:
```
Check constraints:
"application_one_not_null" CHECK (import_application_id IS NULL OR export_application_id IS NULL)
"application_one_null" CHECK (import_application_id IS NOT NULL OR export_application_id IS NOT NULL)
```
Test to check they work as expected:
```
>>> WithdrawApplication.objects.create(request_by=me)
django.db.utils.IntegrityError: new row for relation "web_withdrawapplication" violates check constraint "application_one_null"
>>> WithdrawApplication.objects.create(request_by=me, import_application=imp, export_application=exp)
django.db.utils.IntegrityError: new row for relation "web_withdrawapplication" violates check constraint "application_one_not_null"
>>> WithdrawApplication.objects.create(request_by=me, …
```
=> ICMSLST-671 Make WithdrawApplication re-usable between import/export.

web/domains/case/_import/urls.py, web/domains/case/_import/views.py, web/domains/case/urls.py, web/templates/web/domains/case/import/manage/prepare-response.html
Cover letters are only used for import applications, so it doesn't make
sense to move them up to case/views level.
=> ICMSLST-682 Clean up import/cover-letter code.

web/domains/case/_import/urls.py, web/domains/case/_import/views.py, web/domains/case/urls.py, web/domains/case/views.py, web/templates/partial/case/export/sidebar-management.html, web/templates/web/domains/case/import/manage/prepare-response.html
Licences are only used for import applications, so it doesn't make sense
to move them up to case/views level.
=> ICMSLST-669 Clean up import/licence code.

mypy.ini, web/tests/conftest.py, web/tests/domains/case/access/factories.py, web/tests/domains/case/access/test_views.py, web/tests/domains/case/fir/factory.py, web/tests/domains/constabulary/factory.py
ICMSLST-651 Reduce xfail tests from 60 to 26.
Also:
* Remove some unused test code.
* Remove randomness from tests.
* Fix randomly failing constabulary test by reducing name length.
=> ICMSLST-651 Reduce xfail tests from 60 to 26.

mypy.ini, requirements-dev.txt, web/auth/views.py, web/domains/case/_import/derogations/views.py, web/domains/case/_import/fa_dfl/views.py, web/domains/case/_import/fa_oil/views.py, web/domains/case/_import/fa_sil/forms.py, web/domains/case/_import/fa_sil/views.py, web/domains/case/_import/models.py, web/domains/case/_import/opt/views.py, web/domains/case/_import/wood/views.py, web/domains/case/export/models.py, web/domains/case/models.py, web/domains/case/utils.py, web/domains/case/views.py, web/domains/file/models.py, web/domains/file/utils.py, web/domains/mailshot/views.py, web/domains/sanction_email/views.py, web/domains/section5/views.py, web/domains/template/views.py, web/flow/models.py, web/migrations/0001_initial.py
This is phase one, still 150+ to go.
In more detail:
* Upgrade mypy, add types-pytz and types-requests.
* Fix is_active mypy issues.
* Ignore attr-defined error for status field.
* Ignore several attributes that aren't defined in base class.
* Import reverse from django.urls, not django.shortcuts.
* Type optional forms.
* Fix type complaints in mailshot/views.py.
* Make all File fields non-nullable.
They do not need to be nullable anymore, we only add valid files to the
database nowadays.
Marking them non-nullable removes mypy complaints about Optional[x].
* Add user_is_contact_of_org method.
* Type applications with a checklist.
* Disable warnings for reverse one_to_one relationships.
* Ignore mypy warnings regarding class type.
* Fix related_file_manager type.
=> ICMSLST-634 Fix/work around mypy issues found by django-stubs.

Makefile, README.md, config/settings/test.py, requirements-dev.txt, run-tests.sh, web/management/commands/add_test_data.py, web/tests/conftest.py, web/tests/domains/case/_import/fa_dfl/test_views.py, web/tests/domains/importer/test_forms.py, web/tests/domains/importer/test_views.py, web/tests/file_upload_handler.py, web/tests/helpers.py, web/utils/validation.py
Changes:
- Add django command to add dummy data to test database
- Add top level fixtures for common things
- Added dummy file upload handler
- Add tests for the following endpoints:
- edit_dfl
- add_goods_certificate
- edit_goods_certificate
- submit_dfl
=> ICMSLST-726 Add tests for FA-DFL applicant views.

web/tests/utils/test_search.py, web/utils/search.py
'In Progress' for 'Case Status' doesn't return anything for agent, importer or case worker.
=> ICMSLST-1103 Remove in progress from search import certificates

web/middleware/common.py
Otherwise non-local environments break.
=> ICMSLST-643 Move show_queries import inside the function.

Dockerfile
Running `docker build -t [tag] .` was failing with an error about missing
the pg_config helper (when installing Python deps). Adding an explicit
dependency on libpq-dev fixes this.
=> ICMSLST-1185 Fix Docker build for the web container

web/domains/case/export/forms.py, web/domains/case/export/urls.py, web/domains/case/export/views.py, web/domains/cat/models.py, web/templates/web/domains/cat/partials/table.html, web/tests/domains/case/export/test_views.py, web/tests/domains/cat/test_models.py
No need for query param or extra redirect hop to "export:choose".
Would still need to extend for the other two application types
=> ICMSLST-1029 Create GMP app from template without query params.

web/templates/messages/messages.html
The Django messages framework is used to provide flash messages to users
on actions like form saves, but we were marking the message text as safe
and at the same time using un-trusted user data (things like the template
name). This meant a user could inject arbitrary markup.
This change stops marking all messages as HTML safe. I don't see anywhere
in the view handlers where we actually expected HTML to be displayed in
a message.
=> ICMSLST-1214 Do not trust message text as HTML-safe (fixes XSS bugs)

web/templates/web/domains/cat/partials/table.html
The path keyword argument was changed, but the template had not been updated,
causing a NoReverseMatch exception when the user visits /cat/ and there are
template objects.
=> ICMSLST-1190 Fix NoReverseMatch exception on template list view

web/domains/case/views/views_misc.py
Previously if "Cancel Authorisation" was pressed, the application row
would appear with no actions. It now has the correct "Manage" action.
=> ICMSLST-1220 Fix status when cancelling authorisation.

web/domains/cat/urls.py, web/domains/cat/views.py, web/templates/web/domains/cat/base_form.html, web/templates/web/domains/cat/partials/table.html, web/tests/domains/cat/test_views.py
In the list of templates ("/cat/"), clicking the _name_ of a template links to a read-only version of the templates, like "/cat/view/[id]/". The read-only view re-uses the editing views, but with form inputs disabled.
=> ICMSLST-1044 Add a read-only version of the application templates

config/settings/base.py, pii-ner-exclude.txt, requirements-base.txt, requirements-dev.txt, web/domains/chief/client.py, web/domains/chief/urls.py, web/domains/chief/views.py, web/tests/domains/chief/test_client.py, web/tests/domains/chief/test_views.py, web/urls.py
The path for the call-back is "/chief/license-data-callback".
New settings for configuring Hawk authentication:
- CHIEF_LICENSE_URL, the icms-hmrc API to send license requests.
- HAWK_AUTH_ID, client ID shared by icms and icms-hmrc (not a secret).
- HAWK_AUTH_KEY, signing key shared by icms and icms-hmrc (secret).
Both HAWK_AUTH_ID and HAWK_AUTH_KEY must be shared with the sender (in our case, the sender is icms-hmrc).
When sending data to the call-back, we must return either a 207 multi status or 208 already reported status. For a 207 response, the body is a JSON object with keys for "accepted" and "rejected", and with values a list of objects like `{"id": <license-id>}`.
=> ICMSLST-1269 Stub methods for CHIEF integration

requirements-base.txt
Older versions of jinja use soft_unicode:
Its deprecated:
It has been fixed in Jinja 3.0.0
=> Upgrade Jinja to fix ci bug.

pii-ner-exclude.txt, web/domains/chief/urls.py, web/domains/chief/views.py, web/menu/menu.py, web/templates/web/domains/chief/_base.html, web/templates/web/domains/chief/failed_batches.html, web/templates/web/domains/chief/failed_licences.html, web/templates/web/domains/chief/pending_batches.html, web/templates/web/domains/chief/pending_licences.html, web/tests/domains/chief/test_views.py
New dashboard views for CHIEF requests and errors:
- /chief/
- /chief/pending-licences/
- /chief/failed-batches/
- /chief/failed-licences/
The 4 views have a stub implementation that lists ImportApplication objects
and the links for actions in each row will be implemented next.
=> ICMSLST-1394 Add the CHIEF dashboard views and navigation

pii-ner-exclude.txt, web/domains/case/app_checks.py, web/domains/case/export/views.py, web/domains/case/utils.py, web/domains/case/views/views_misc.py, web/domains/case/views/views_prepare_response.py, web/domains/case/views/views_search.py, web/domains/case/views/views_variation_request.py, web/tests/domains/case/test_utils.py, web/tests/domains/case/views/test_views_misc.py, web/tests/domains/case/views/test_views_search.py, web/tests/domains/case/views/test_views_variation_request.py, web/utils/search/app_data.py
Changes:
- Create a draft licence/certificate when opening a VR.
- Archive the licence/certificate when cancelling a VR.
- Filter out archived licences from search results.
- Create an export licence certificate when creating an export app.
- Archive old licence when completing a case
- Set completion date when completing an application.
=> ICMSLST-1476 Update licence/certificate when a variation is requested.

pyproject.toml, web/domains/case/views/views_misc.py, web/tests/domains/case/views/test_views_misc.py
Export applications can change the application countries and brands via a variation request / application update.
Therefore clear any existing document references before creating them.
=> ICMSLST-1442	Clear export app document references before authorising.

config/gunicorn.py
This is silly, but part of a belt-and-braces approach to security.
=> ICMSLST-1537 Obscure the default gunicorn `Server` response header

pii-ner-exclude.txt, web/domains/case/_import/fa/views.py, web/domains/case/_import/fa_sil/views.py, web/templates/web/domains/case/import/fa-sil/add-section5-document.html, web/templates/web/domains/case/import/fa-sil/edit.html, web/templates/web/domains/case/import/fa-sil/view-verified-section5.html, web/templates/web/domains/case/import/fa/certificates/manage.html
Changes:
- Remove section 5 documents from edit view.
- Add section 5 documents to certificates list view.
- Update error URL's in submit view to navigate to certificate list view.
- Delete section 5 documents when submitting if section5 is not selected.
=> ICMSLST-1460 Move FA-SIL section 5 documents to certificates page.

config/settings/base.py, config/settings/local.py, config/settings/production.py, config/settings/test.py
This is useful for local development. When deployed to Cloud Foundry, we
also use this as a base logging config, except for the "production" env.
=> ICMSLST-1619 Show DEBUG logging by default

web/templates/web/domains/case/import/fa-sil/view.html, web/templates/web/domains/case/import/fa/certificates/manage.html, web/templates/web/domains/case/import/partials/fa-sil/verified-section5-authorities.html
A user who creates a SIL app can now choose verified section 5 authorities
as well as upload additional authority documents.
=> ICMSLST-1615 Fix to show verified and user section 5 authorities together.

.pre-commit-config.yaml, Makefile, documentation/playwright.md, pii-ner-exclude.txt, web/end_to_end/test_create_fa_sil_application.py, web/management/commands/add_dummy_data.py, web/management/commands/add_test_data.py, web/tests/domains/firearms/test_views.py
Other changes:
- Set "python-pytest" as default playwright codegen target.
- Add dummy ObsoleteCalibre / ObsoleteCalibreGroup test data.
- Downgrade mypy for now (ICMSLST-1807 to fix the new mypy issues)
=> ICMSLST-1802  Add end to end test for FA-SIL application.

pii-ner-exclude.txt, web/domains/case/models.py, web/domains/case/services/document_pack.py, web/domains/case/utils.py, web/domains/case/views/views_misc.py, web/domains/case/views/views_prepare_response.py, web/domains/case/views/views_search.py, web/tests/domains/case/_import/fa_oil/test_views.py
Fixes incorrect licence details being shown on the search screen.
Changes:
- Update prepare response view to only fetch licence when needed.
- Archive pack when an application is withdrawn.
- Archive pack when an application is stopped.
- Add several docstrings.
- Fix duplicate PROCESS task when a withdrawal request is refused.
- Refactor debug function used to show application history.
=> ICMSLST-1900 Archive draft packs when closing or withdrawing an app.

pii-ner-exclude.txt, web/domains/case/views/views_prepare_response.py, web/templates/partial/case/import/sidebar-management.html, web/templates/web/domains/case/import_licence_history.html, web/templates/web/domains/case/manage/prepare-response.html
Changes:
- Set revoked licence in response prep context
- Show warking when a licence is revoked
- show ILB admin "Responses" link when a case is revoked.
- Add suffix to response header when revoked.
=> ICMSLST-1908 Show revoked licence on response preparation screen.

data_migration/management/commands/_types.py, data_migration/management/commands/check_data_counts.py, data_migration/management/commands/config/data_counts.py, data_migration/management/commands/import_v1_data.py, data_migration/queries/data_counts.py, data_migration/queries/export_application/cfs.py, data_migration/queries/export_application/com.py, data_migration/queries/export_application/gmp.py, data_migration/queries/import_application/fa/dfl.py, data_migration/queries/import_application/fa/oil.py, data_migration/queries/import_application/fa/sil.py, pii-ner-exclude.txt
* Add flag to data counts to only show fails
* Fix queries pulling application variation requests from V1
* Fix method to add missing document packs to export applications
* Exclude submitted export applications with no case reference from data migration
* Add adjustments to data counts to account for data which has been excluded from data migration
** Add adjustments rather than change the query checking the V1 data as it will flag the issue if it occurs again rather than just automatically excluding the data
=> ICMSLST-1905 Fix missing variation requests in data migration

pii-ner-exclude.txt, web/domains/case/views/mixins.py, web/domains/case/views/views_search.py, web/jinja2.py, web/static/web/js/pages/search-export.js, web/static/web/js/pages/search-import.js, web/templates/web/domains/case/search/export/case_details.html, web/templates/web/domains/case/search/export/results-table.html, web/templates/web/domains/case/search/export/search-form-fields.html, web/templates/web/domains/case/search/import/case_details.html, web/templates/web/domains/case/search/import/search-form-fields.html, web/templates/web/domains/case/variation-request-add.html, web/templates/web/domains/case/variation-request-update.html, web/tests/domains/case/views/test_views_search.py, web/tests/helpers.py, web/utils/search/api.py
Changes:
- Add has_object_permission hook to ApplicationTaskMixin.
- Restrict reassignment feature to only work for ILB admin users.
- Implement has_object_permission for RequestVariationUpdateView class.
- Add jinja function to show correct view case url.
- Add missing Sent Responses urls to variation request views.
- Add missing permission tests for all search views.
=> ICMSLST-1958 Update search views permissions and update template links.

web/domains/case/_import/forms.py, web/domains/case/_import/views.py, web/management/commands/add_dummy_data.py, web/tests/domains/case/_import/textiles/test_admin_views.py, web/tests/domains/case/_import/textiles/test_views.py, web/tests/domains/workbasket/test_views.py
Changes:
- Update CreateImportApplicationForm to return correct importers and agents.
- Fix bug when searching for agent office
- Refactor importers_with_agents to use values_list
- Add a second agent importer.
- Fix several tests still explicitly creating test clients.
- Fix delete_endorsement view permissions (it's an ILB admin view).
=> ICMSLST-1992 Update create import application view to use new permissions.

web/domains/contacts/views.py, web/tests/domains/contacts/test_views.py
Users with "manage_contacts_and_agents" object permission can now add and delete organisation contacts.
=> ICMSLST-2064 Fix permissions on contact views.

web/management/commands/add_dummy_data.py, web/management/commands/create_icms_groups.py, web/menu/menu.py, web/permissions/service.py, web/tests/domains/exporter/test_views.py, web/tests/domains/importer/test_views.py, web/tests/permissions/test_service.py
The ILB Case Officers group should have feature parity with V1 users. The V2 group is a combination of V1 Team roles:
- Country Super Users
- ILB Admin Users
- ILB Case Officers
A few menu items have been removed in V2 that aren't in V1. They can still be accessed by the Importers / Exporters views.
=> ICMSLST-1827 Update ILB Case officer group permissions.

.env.example, README.md, config/settings/base.py, docker-compose.yml, pii-ner-exclude.txt, web/domains/case/export/models.py, web/domains/case/export/views.py, web/domains/workbasket/views.py, web/management/commands/add_dummy_data.py, web/management/commands/utils/add_application_type_data.py, web/menu/menu.py, web/templates/partial/case/export/sidebar-create.html, web/templates/web/domains/workbasket/workbasket.html
The organisation contact groups have feature parity with V1 users.
V2 users have extra features that V1 users do not since upgrading ILBTEST.
All differences found are going to be discussed with ILB, the stories are listed below:
- ICMSLST-2082
- ICMSLST-2087
- ICMSLST-2088
Other changes:
- Update application types shown when developing ICMS.
- Set is_active to correct value for all application types
- Add setting to enable all application types if needed.
- Update page_title for workbasket view.
- Fix export application sidebar to only show active application types.
=> ICMSLST-1737/1738/1739 Update organisation contact group permissions.

README.md, pii-ner-exclude.txt, web/management/commands/add_dummy_data.py, web/management/commands/add_test_data.py, web/management/commands/create_icms_groups.py, web/permissions/context_processors.py, web/permissions/service.py, web/templates/web/domains/case/view_case.html, web/tests/conftest.py, web/tests/domains/user/test_forms.py, web/tests/permissions/test_context_processors.py, web/tests/permissions/test_service.py
Changes:
- Add new "NCA Case Officer" group.
- Add new nca_admin test user.
- Add can_edit_application to user_obj_perms template object.
- Update AppChecker.can_view to check search_all_cases permission.
=> ICMSLST-1895 Add NCA Case Officer group.

config/settings/test.py, data_migration/management/commands/import_v1_files_to_s3.py, data_migration/management/commands/utils/db_processor.py, data_migration/queries/files_v1.py, data_migration/tests/test_db_processor.py, data_migration/tests/test_import_v1_files_to_s3.py, pii-ner-exclude.txt, requirements-base.txt, requirements-dev.txt, web/utils/s3.py
Command to import files into s3
- Adds command
- Adds tests for command
- Supported options `--limit` `--ignore-last-run` `--queries` `--s3-file-prefix` `--number-of-rows` `--count-only` 
Known issues (other tasks still to do)
- Command is using the wrong queries and should use the queries found in `files.py`
- The last run data is only written to s3 on a successful run and not if an error occurs
=> ICMSLST-2063 - Import and refactor of import files to s3 code

data_migration/management/commands/post_migration.py, data_migration/queries/permissions.py, data_migration/tests/test_e2e.py, data_migration/tests/test_e2e_users.py, data_migration/tests/utils/user_data.py, pii-ner-exclude.txt
Apply importer and exporter object permissions after the post data migration. The queries to select the data narrow down the permissions to only select data for `IMP_EXPORTER_AGENT_CONTACTS` and  `IMP_EXPORTER_CONTACTS` for exporters and `IMP_IMPORTER_AGENT_CONTACTS` and  `IMP_IMPORTER_CONTACTS` for importers along with returning the organisation id the user's permissions are for. The user permissions are then applied based on their roles in the organisation `VIEW` to view, `EDIT` or `VARY` to edit, `AGENT_APPROVER` to manage contacts.
=> ICMSLST-2077 Data Migration Importer and Exporter Object Permissions

data_migration/README.md, data_migration/management/commands/export_from_v1.py, data_migration/management/commands/import_v1_files_to_s3.py, data_migration/management/commands/utils/db_processor.py, data_migration/queries/files.py, data_migration/tests/test_db_processor.py, data_migration/tests/test_import_v1_files_to_s3.py, pii-ner-exclude.txt
- Removed `--s3-file-prefix` option in favour of prefixing the query name to the file path within the queries themselves
- Renamed `--number-of-rows` to `--batchsize` to be more consistent with other data migration commands
- Created an option  `--run-data-batchsize` to replace `SAVE_RUN_DATA`
- Introduced query aliases `small` / `large` that groups queries based on total data (small below 1.5 GB)
- Updated Readme
=> ICMSLST-2098 Refactor Import to s3 script options

web/notify/email.py, web/notify/notify.py, web/notify/utils.py, web/templates/web/domains/case/manage/case-emails.html, web/tests/notify/test_notify.py
Pass attachment ids instead of attachment files to send_email so emails with attachments can be called as a celery task. Fetch the files from S3 within send_email task instead
=> ICMSLST-2061 Fetch Email Attachments in Celery Task

config/celery.py, web/notify/notify.py, web/tests/notify/test_notify.py
* Fixing the task to send to constabulary contacts instead of ilb admin users
* Removing the task from the celerybeat schedule until it is confirmed constabulary contacts will be using the system to manage firearms authorities
=> Send firearms authority notifications to constabulary contacts

config/settings/base.py, config/settings/local.py, docker-compose.yml, web/tests/utils/pdf/test_generator.py, web/utils/pdf/generator.py
Move logic required to get static files domain to pdf/generator.py.
=> ICMSLST-2315 Remove PDF_DEFAULT_DOMAIN setting.

config/settings/base.py, config/settings/test.py, web/mail/messages.py, web/mail/url_helpers.py, web/notify/utils.py, web/tests/helpers.py, web/tests/mail/test_emails.py, web/tests/mail/test_url_helpers.py
All emails use the caseworker domain by default, this will change in ICMSLST-2313.
=> ICMSLST-2314 Remove invalid DEFAULT_DOMAIN setting.

web/domains/importer/views.py, web/management/commands/create_icms_groups.py, web/tests/conftest.py, web/tests/domains/importer/test_views.py
ILB confirmed it is useful for NCA Case Offers to be able to search importer records.
=> ICMSLST-2121 Add importer_regulator permission to NCA Case Officer group.

web/static/web/css/fox.css
The default render changed from Form.as_ul to Form.as_div in django 4.1.
=> ICMSLST-1779 Fix RadioSelectInline css to render elements inline.

.coveragerc, pii-ner-exclude.txt, web/domains/template/context.py, web/domains/template/utils.py, web/management/commands/utils/add_template_data.py, web/templates/pdf/export/cfs-certificate.html, web/templates/web/domains/case/export/manage/export-prepare-response.html, web/templates/web/domains/case/manage/prepare-response.html, web/tests/domains/template/test_utils.py, web/tests/utils/pdf/test_generator.py, web/utils/pdf/utils.py
Adding translations to the CFS PDF certificates using the partial implementation that has already been added as well as the data in V1.
CFS_DECLARTION_TRANSLATION templates are used to fetch the translation for the declaration
CFS_SCHEDULE_TRANSLATION templates are used to fetch the paragraphs that are translated within the cfs schedule
=> ICMSLST-1831 CFS Schedule PDF Translations

pii-ner-exclude.txt, web/templates/model/list.html, web/tests/domains/commodity/test_views.py, web/tests/domains/constabulary/test_views.py, web/tests/domains/firearms/test_views.py, web/tests/domains/importer/test_views.py, web/tests/domains/legislation/test_views.py, web/tests/domains/mailshot/test_views.py, web/tests/domains/section5/test_views.py, web/tests/domains/template/test_views.py, web/views/views.py
All classes that inherit from ModelFilterView no longer perform a search until the search button is pressed.
Admin views updated:
- Importers
- Exporters
- Mailshots
- Commodities
- Constabularies
- Sanction Emails
- Obsolete Calibres
- Section 5 Clauses
- Product legislation
- Manage Country Groups
- Templates
- Web User Accounts
=> ICMSLST-1328 Prevent search on all views until search has been pressed.

data_migration/management/commands/_types.py, data_migration/management/commands/config/run_order/files.py, data_migration/management/commands/import_v1_files_to_s3.py, data_migration/queries/export_application/export.py, data_migration/queries/files.py, data_migration/queries/import_application/licence.py, data_migration/tests/test_import_v1_files_to_s3.py, pii-ner-exclude.txt
Fixed the following:
- Missing query parameters after script restart
- Duplicate files (associated to none complete applications) no longer processed
- Support for alternative `limit by field` added (`secure_lob_ref_id` now default)
- Sql order bys updated to use `secure_lob_ref_id` where possible
- Files with the same date time as the last file processed are now processed
=> ICMSLST-2386 - Fix restarting of import files from v1 cmd

pii-ner-exclude.txt, web/domains/chief/serializers.py, web/domains/exporter/forms.py, web/domains/importer/forms.py, web/domains/office/forms.py, web/forms/fields.py, web/forms/utils.py, web/tests/domains/importer/test_views.py
CHIEF/CDS requires trader postcodes to be valid and will error if not. Add form validation to reduce the number of errors raised in this way.
=> ICMSLST-1935 Add postcode form validation to importer office views.

web/domains/workbasket/actions/applicant_actions.py, web/domains/workbasket/app_data.py, web/tests/domains/workbasket/test_views.py
Applications were being incorrectly filtered by checking a user had every permission in a list rather than any one of.
Applicant actions have been updated to match the associated view permission logic.
=> ICMSLST-2396 Fix permission checking in applicant workbasket.

.env.circleci, .env.local-docker, config/env.py, config/settings.py, config/settings_test.py, pii-ner-exclude.txt, web/mail/api.py, web/mail/backends.py, web/tests/mail/test_api.py
- Retries any HTTPError thrown by the send email task.
- The retry parameters are settings so these can be tweaked on each platform if necessary.
- The rate limit seems to only affect the mail queue although it does seem to be a limit per worker which needs to be taken in to consideration when setting the value.
- The default rate limit is 1000/m. Making an assumption that we have a max of 2 workers
- If maximum retries are exceeded the exception is logged to sentry. The information in sentry is sufficient to determine which task id failed and what email type was being processed.
- By default retry jitter is set to true which will incorporate an exponential back off resulting in tasks not being retried all at the same time.
- Note if testing with low rate limits …
=> ICMSLST-2349 - Rate limit and retry for mail task

.gitignore, .pre-commit-config.yaml, config/env.py, config/settings.py, config/settings_local.py, requirements-dev.txt, web/utils/pdf/generator.py
updating pre-commit hooks
adding REDIS_URL to .env to support non-docker setups
adding local.env to .gitignore
formatting .pre-commit-config.yaml
adding celery always_eagier and making s3_endpoint url compatible outside of docker.
updating pre-commit package to deal with black changes
=> Allowing non-docker setup, optimising pre-commit hooks, celery debugging.

pii-ner-exclude.txt, web/domains/case/_import/fa_oil/forms.py, web/tests/conftest.py, web/tests/domains/case/_import/fa_oil/test_forms.py
Disabling country dropdowns in the OIL form that only have 1 possible options - "Any Country"
=> ICMSLST-1259 - Locking dropdowns with only 1 option

config/env.py
Model is configured to ignore extra attributes and the user-provided key only appears in the dev and staging environments.
=> Remove "user-provided" key from VCAPServices environment variable.

web/templates/pdf/import/cover-letter.html
ICMLST-2477
adding organisation name and postcode back to the cover letter to align with V1 PDFs
=> ICMSLST-2477 - Adding organisation name/postcode to cover letter

web/static/web/css/pdfs/sanctions-licence-style.css, web/templates/pdf/import/sanctions-licence.html
ICMSLST-2330
Fixing page breaks in sanctions licences. Now endorsements that are too long are manually split between multiple pages.
=> ICMSLST-2330 - Fix Sanctions PDF page breaks

data_migration/management/commands/config/run_order/import_application.py, data_migration/models/case.py, data_migration/queries/import_application/derogations.py, data_migration/queries/import_application/fa/dfl.py, data_migration/queries/import_application/fa/oil.py, data_migration/queries/import_application/fa/sil.py, data_migration/queries/import_application/licence.py, data_migration/queries/import_application/opt.py, data_migration/queries/import_application/quota.py, data_migration/queries/import_application/sanctions.py, data_migration/queries/import_application/sps.py, data_migration/tests/test_e2e.py, data_migration/tests/utils/ia_data.py, pii-ner-exclude.txt
- Licence unique references need to exist before import applications due to fk, so extracting out from licence docs into separate query
- Not all import applications have a licence reference
=> Data Migration - Fix Licence Unique Reference Migration

Procfile, apt.yml, manifest.yml, pii-ner-exclude.txt, scripts/celery-worker-entry.sh, scripts/entry.sh
Changes:
- Add apt-buildpack to install playwright system dependencies.
- Add entry script for celery worker to install playwright browser.
- Install playwright browser in web entry script.
- Scale celery_worker process to fix memory issues:
- cf scale icms-dev -k 2G --process celery_worker
- cf scale icms-dev -m 2G --process celery_worker
The celery_worker disk space increase is to accommodate the extra install space required for chromium.
The celery_worker RAM increase fixes an out of memory exception caused when signing the PDF.
=> ICMSLST-2505 Add requirements for running Playwright in Cloud Foundry.

Makefile
Use same container to run both commands.
=> Speed up migration commands in makefile.

config/settings.py, web/middleware/common.py, web/tests/middleware/test_common.py
The DBT Platform healthcheck uses the machine IP address as the host when calling the pingdom/ping.xml endpoint. This throws an exception as the IP address is not a valid site.
=> ICMSLST-2536 Add middleware to skip adding site attribute to request obj.

web/static/web/css/components/signature.css
Enforcing a standardised width for the PDF signature image and setting a max height so it doesn't overflow.
=> ICMSLST-2511 - Fix PDF signature image sizing

pii-ner-exclude.txt, web/templates/web/domains/case/import/fa/partials/report-list.html
=> ICMSLST-1355 - Display supplementary report details in correct order

pii-ner-exclude.txt, scripts/reset-local-docker-db
Commands need to be separate as `add_reports_data` was interrupted as a argument to the other command.
=> Fix for add report data when resetting local db

data_migration/queries/export_application/export.py, data_migration/queries/import_application/licence.py, pii-ner-exclude.txt
Revoked status was added to document after the data migration was written. Add revoked status to the queries pulling the document pack data from V1
=> Data Migration - Correct Document Pack Revoked Statuses

pii-ner-exclude.txt
PII secrets checking currently runs as a pre-commit hook, meaning it only scans files that have been touched as part of the commit. This works well, however it means that casual changes to file X result in a full scan of the entire file meaning that lines of code that have remain unchanged are suddenly picked up as potentially containing sensitive data.
This PR runs the secret checker on the entire codebase such that previously 'missed' secrets have all been flagged and excluded, meaning that the only time the secret checker should flag a new bit of potentially dangerous information is when it has just been added to the codebase.
=> Scanning the entire codebase for PII with pii-secret-check-hooks

playwright/Dockerfile
End to end tests don't run if there is a new version of the playwright image available.
This sets the image to use the latest tag
=> Playwright image updated to latest

web/templates/pdf/export/com-certificate.html
A signature was unable to be applied to COM certificates because the QR code was WAY too big and so obscured the placeholder signature text, this is because the com-certificate.html doesn't actually inherit from the base-certificate.html template and so never got the certificate-style.css import. This has now been manually added.
Before:
After:
=> ICMSLST-2538 - COM certificate signing error

requirements-base.txt
Releases after 24.0.0 remove the OpenSSL.crypto.PKCS12 module which is used for testing PDF certificate signing
=> Pinning PyOpenSSL to 24.0.0

pii-ner-exclude.txt, web/domains/importer/forms.py, web/domains/importer/views.py, web/tests/domains/importer/test_forms.py, web/tests/domains/importer/test_views.py
As per the ILB Team feedback, older Importer records may not have an EORI Number, as previously is was not a mandatory value.
The following changes should be implemented:
Check if an Importer has an EORI Number entered when the Admin initiates editing of the Importer record
When [Save] is used, if the EORI Number was populated on entry, maintain mandatory value checks on this field
When [Save] is used, if there was no EORI Number on the record, skip the mandatory value checks on this specific field only
=> ICMSLST-1624 - allow update of historical record without EORI Number present.

web/tests/views/test_cookie_views.py, web/views/views.py
Fixing GA consent acceptance cookies, not setting a dictionary with multiple values, just the main usage one.
=> ICMSLST-2524 - Fixing GA cookie consent

web/static/web/css/pdfs/fa-common-licence-style.css, web/static/web/css/pdfs/licence-and-certificate-common-style.css, web/templates/pdf/shared/fa-licence-base.html
Increasing default text size in V2 PDFs so they align with V1 styling.
Before:
After:
=> ICMSLST-2480 - V2 documents are smaller than v1

data_migration/management/commands/config/data_counts.py, data_migration/queries/permissions.py, data_migration/queries/utils.py, pii-ner-exclude.txt
Only migrate permissions for suspended / active users. Inactive / cancelled / blocked users will need to go through the process of obtaining their user /  group permissions again should they sign up with staff sso / one login.
=> ICMSLST-2572 Data Migration - Do not migrate permissions for inactive / cancelled users

pii-ner-exclude.txt, web/tests/auth/auth.py, web/tests/conftest.py, web/tests/domains/cat/test_views.py
Changes:
- Add CATListView tests.
- Extend test_can_create_template test to test all app types.
- Add edit template tests for all steps for all app types.
- Add CFSManufacturerUpdateView tests.
- Add CFSManufacturerDeleteView tests.
- Add CFSScheduleTemplateAddView tests.
- Add CFSScheduleTemplateCopyView tests.
- Add CFSScheduleTemplateDeleteView tests.
=> ICMSLST-2544 Add Unittests for CAT views.

config/settings.py
This was because the variable in the settings file was not named correctly, and so img-src was not getting added to the CSP header.
=> img-src CSP header not being added.

.pre-commit-config.yaml, pii-ner-exclude.txt, web/domains/case/export/views.py, web/domains/cat/views.py, web/management/commands/add_dummy_data.py, web/templates/web/domains/case/export/cfs-edit-schedule.html, web/templates/web/domains/case/export/partials/cfs/schedule-products.html, web/templates/web/domains/cat/cfs/edit-schedule.html
Changes:
- Add common partial template to use in CFS Edit and template view.
- Add CFS Schedule Template products to add_dummy_data
New section added to the CFS Schedule Template edit view:
=> ICMSLST-2564 Add schedule products to CFS Schedule Template view. 

web/domains/commodity/forms.py
Adding 'Any' as an option to fields on the CommodityGroup search filter, removing redundant field, and fixing label.
Before:
After:
=> ICMSLST-1299 - Commodities - Add 'Any' as default search option for Commodity Group fields.

web/domains/commodity/forms.py
Adding 'Any' option on CommodityFilter.
Before:
After:
=> ICMSLST-1298 - Commodities - Add 'Any' as default search option for Commodity Type.

pii-ner-exclude.txt, web/domains/cat/forms.py, web/domains/cat/urls.py, web/domains/cat/views.py, web/end_to_end/cat/test_create_cfs_cat.py, web/end_to_end/utils.py, web/management/commands/add_dummy_data.py, web/templates/web/domains/case/export/partials/cfs/schedule-product-list.html, web/templates/web/domains/case/export/partials/cfs/schedule-products.html, web/templates/web/domains/cat/cfs/product-template-create.html, web/templates/web/domains/cat/cfs/product-template-update.html, web/tests/domains/cat/test_views.py
Changes:
- Add CFSScheduleTemplateProductCreateView view.
- Add CFSScheduleTemplateProductUpdateView view.
- Add CFSScheduleTemplateProductDeleteView view.
- Refactor shared templates to use correct urls.
- Add E2E tests for CFS schedule product template views.
- Add unittests for CFS schedule product template views.
Add Product / Edit / Delete links are now correct:
Add Product view:
Edit Product view (no product types / active ingredients:
Edit product view (existing products)
Edit product view showing formset error handling (checks for duplicates)
=> ICMSLST-2564 Add several CFS Schedule Product Template views.

data_migration/tests/test_xml_parser.py, data_migration/tests/utils/xml_data/fa.py, data_migration/utils/xml_parser/import_application.py, pii-ner-exclude.txt
The Supplementary Report `GOODS_ITEM_LIST` xml could potentially list the goods in a different order to those found within the `COMMODITY_LIST` xml.  
Data Migration takes the goods from the commodity list and inserts them into the database.
When associating the additional Supplementary data it was assumed the order would be the same as those found within the commodity list, this is not the case. 
The fix looks at the `GOODS_ITEM_LIST` and in particular the `GOOD_ITEM_ID` item where the index (ordinal) of the `COMMODITY_LIST` is appended to the the goods description.
The fix takes this index and uses this to associate the Supplementary data with the correct good.
=> ICMSLST-1899 - Fix to good item line ordinal

pii-ner-exclude.txt, web/domains/case/export/forms.py, web/domains/case/export/urls.py, web/domains/case/export/views.py, web/domains/cat/forms.py, web/domains/cat/urls.py, web/domains/cat/views.py, web/templates/forms/forms.html, web/templates/web/domains/case/export/cfs-product-create-multiple.html, web/templates/web/domains/case/export/partials/cfs/schedule-products.html, web/templates/web/domains/cat/cfs/product-template-create-multiple.html, web/tests/domains/case/export/test_views.py, web/tests/domains/cat/test_views.py, web/views/generic.py
Changes:
- Add CFSScheduleProductCreateMultipleView view
- Add CFSScheduleTemplateProductCreateMultipleView view.
- Add reusable InlineFormsetView view.
- Add unittests for new views.
- Add submit_button form macro.
- Add missing type hints to cfs views.
New button to add multiple products in both template editor and CFS application:
New form in template editor to add multiple products:
New form in CFS application to add multiple products:
=> ICMSLST-2594 Add "Add Multiple Products" view to Edit CFS Schedule.

web/apps.py, web/models/lookups.py, web/tests/utils/search/test_search.py, web/utils/search/api.py
Search code now uses __ilike for all wildcard filtering and adds a "%" on to the end of search strings to improve search results.
=> ICMSLST-2574 Add ILike db model lookup to improve wildcard filtering.

web/jinja2.py, web/templates/web/menu/menu.html
Previously this was implemented for a few of the test users by hardcoding the username in the surname field when creating the dummy data.
=> Add username to users name in top menu for debugging purposes.

web/templates/web/domains/case/manage/case-email-box.html
Added a 'edit response' button to the bottom of GMP HSE emails view. Also increased the spacing to align with V1 and changed the 'record response' button text if a response is already there.
Before:
After:
=> ICMSLST-1586 - Manage Case - show all emails and responses on the same page.

web/domains/case/_import/fa/forms.py, web/tests/domains/case/_import/fa_oil/test_forms.py
=> ICMSLST-1260 - Firearms OIL - Application - Certificate Type field does not need drop-down list.

config/urls.py, pii-ner-exclude.txt, web/flow/errors.py, web/tests/domains/case/export/test_views.py, web/tests/domains/case/views/test_views_misc.py, web/tests/domains/case/views/test_views_search.py, web/tests/views/test_views.py, web/utils/sentry.py, web/views/__init__.py, web/views/views.py
ProcessError is raised when a resource is accessed when it doesn't have the expected status or active task.
Returning a 403 instead of a 500 status code is more appropriate.
=> ICMSLST-2598 Return a 403 status code when ProcessError is raised.

pii-ner-exclude.txt, web/domains/case/app_copy.py, web/domains/case/export/forms.py, web/domains/case/export/models/cfs_models.py, web/domains/case/export/views.py, web/domains/cat/forms.py, web/domains/cat/views.py, web/management/commands/add_dummy_data.py, web/management/commands/add_test_data.py, web/static/web/js/pages/cfs-schedule-edit.js, web/templates/web/domains/case/export/cfs-view.html, web/templates/web/domains/case/export/partials/cfs/edit-schedule-form-content.html, web/tests/domains/case/export/test_forms.py, web/tests/domains/legislation/test_forms.py, web/tests/domains/legislation/test_views.py
Changes:
- Add is_biocidal_claim method to CFSScheduleABC.
- Display biocidal_claim field in template based on is_biocidal_claim.
- Add is_biocidal_claim context to cfs schedule edit and template view.
- Remove showIsBiocidalClaim call on page load.
- Update cfs-view.html to check is_biocidal_claim() before showing value.
- Remove "--------" option from biocidal_claim choices.
- Move clean logic to submit form rather than edit form.
- Clear biocidal_claim value when no biocidal_claim legislations are selected.
- Add dummy and test ProductLegislation record.
- Rename EditCFScheduleForm to EditCFSScheduleForm.
Before:
After:
Submit screen checking value is set (when required):
Edit screen showing field is required (after clicking link on Schedule 1 screen)
=> ICMSLST-2566 Several fixes relating to biocidal_claim field.

data_migration/management/commands/_base.py, data_migration/management/commands/export_from_v1.py
Connection in dbt platform will timeout if nothing is printed to stdout in 10 mins. Making sure a record count is printed every minute so that it doesn't time out on long running queries.
=> ICMSLST-2639 Data migration logging improvements

data_migration/management/commands/_base.py, data_migration/management/commands/export_from_v1.py, data_migration/queries/import_application/licence.py
The cross join in the query was filtering to only licences that had been revoked. Change the cross join to not join on the revoke element of the xml and instead the root element.
=> ICMSLST-2641 Data Migration - Fix import licence query

web/static/web/js/pages/withdrawals.js
Response box was not being shown due to JS not matching `rejected===REJECTED`
=> ICMSLST-2626 - Rejected withdrawals are not being updated in the status. There is no way to reject a withdrawal

data_migration/management/commands/config/data_counts.py, data_migration/queries/data_counts.py, data_migration/queries/import_application/sanctions.py, data_migration/tests/test_e2e_inactive.py, data_migration/tests/test_xml_parser.py, data_migration/utils/xml_parser/import_application.py, pii-ner-exclude.txt
- Add post migration checks to check all sanctions apps have sanctions goods and that no sanctions emails have been added (currently none to migrate)
- Reverse order of sanctions goods on the sanctions applications
- Fix query to pull data for applicant's reference correctly
=> ICMSLST-2444 Data Migration - Sanctions Tests and Fixes

.circleci/config.yml, .env.circleci, pii-secret-exclude.txt, requirements-dev.txt, web/tests/domains/importer/test_views.py
Refactoring our CircleCI config to;
- not do all of our checks within docker, circleci is already running a kind-of docker
- split up code hygiene (black, linters...etc.) and the actual testing jobs as they have no dependencies and can be ran in parallel
- run the test suite itself in parallel between 10 different workers
- store test artifacts in circleCI along with codecov, helping to speed up subsequent runs
=> ICMSLST-2535 - CircleCI test parallelisation

web/domains/case/_import/fa/urls.py, web/domains/case/_import/fa/views.py, web/templates/web/domains/case/import/fa/provide-report/report-info.html, web/templates/web/domains/case/view_case.html, web/tests/domains/case/_import/fa/test_views.py, web/tests/helpers.py, web/tests/utils/search/test_search_actions.py, web/utils/search/actions.py, web/utils/search/app_data.py, web/utils/search/utils.py
Changes:
- Remove Provide Supplementary Report action from ILB search.
- Only show Confirm Reporting Complete when report is not complete
- Only show ProvideSupplementaryReportAction when report is not complete.
- Add ILB Admin ViewFirearmsReportDetailView view.
Completed Provide report view when viewing as applicant: 
Completed Provide report view when viewing as caseworker: 
In Progress Provide report view when viewing as applicant: 
In Progress Provide report view when viewing as caseworker:
=> ICMSLST-2652 Supplementary Report fixes.

pii-ner-exclude.txt, web/domains/case/_import/sanctions/forms.py, web/domains/commodity/forms.py, web/domains/commodity/views.py, web/tests/domains/case/_import/sanctions/test_forms.py
Changes:
- Check consignment and origin country when checking sanctioned countries.
- Check consignment and origin country when filtering commodities.
- Add Application Type filter to Commodity Group search.
**Sanctioned country must be either origin or consignment country or both.**
When adding Goods it will check both countries for usage records (used to filter commodities)
**Example application (choosing Russia and North Korea)**
**The available commodities in the Add Goods page:**
**Edit Commodity group pages (showing the commodities available to the sanctions application)**
=> ICMSLST-2666 Sanctions application form country changes

pii-ner-exclude.txt, web/tests/utils/pdf/test_utils.py, web/utils/pdf/utils.py
Added [another bug](https://uktrade.atlassian.net/browse/ICMSLST-2708) to revisit this as the same problem is in one of the reports.
Once I have written tests and fixed ICMSLST-2708 I hope to remove some of the duplication relating to fetching FA-SIL goods.
I believe there are at least 3 places that fetch FA-SIL goods places that could do with a refactor.
=> ICMSLST-2673 Fix section 5 goods having hardcoded subsection in pdf.

pii-ner-exclude.txt, web/reports/interfaces.py, web/reports/serializers.py, web/reports/utils.py, web/tests/reports/test_report_interfaces.py, web/tests/utils/pdf/test_utils.py, web/utils/pdf/utils.py
Update the code used to generate goods descriptions in the SILFirearmsLicenceInterface report.
This change does nothing to address the fact that we create fa-sil goods descriptions in 4 separate places.
- Chief serializers 
- Email Template context
- Report data
- PDF licence context
=> ICMSLST-2708 Fix FA-SIL goods descriptions in reports.

pii-ner-exclude.txt, web/domains/case/app_checks.py, web/domains/case/utils.py, web/domains/case/views/views_update_request.py, web/domains/workbasket/app_data.py, web/templates/partial/case/export/sidebar-management.html, web/templates/partial/case/import/sidebar-management.html, web/templates/web/domains/case/manage/list-update-requests.html, web/tests/domains/case/_import/sanctions/test_views.py, web/tests/domains/case/views/test_views_update_request.py
Changes:
- Change withdraw / close request button label depending on status.
- Update submit logic to check for incomplete update requests.
- Mark withdrawn update requests as inactive instead of responded.
- Fix workbasket query that retrieves open URs to filter active records.
- Update update request count on caseworker sidebars.
- ICMSLST-2737 Email ILB when an user resubmits an application.
Initial caseworker view to send an update request:
Caseworker view after sending an update request (new Withdraw Request button)
Initial applicant view when viewing an update request:
Applicant view after submitting response to request (Status stays as Update In Progress)
Caseworker edge case showing warning if they try to withdraw an in progress update request:
Caseworker view showing a Close …
=> ICMSLST-2699 Add support to withdraw an update request.

pyproject.toml, requirements-base.txt, web/static/web/css/pdfs/certificate-style.css, web/static/web/css/pdfs/cfs-certificate-style.css, web/static/web/css/pdfs/gmp-certificate-style.css, web/templates/pdf/export/cfs-certificate.html, web/templates/pdf/export/gmp-certificate.html, web/templates/pdf/shared/pdf_header.html, web/utils/pdf/generator.py, web/utils/pdf/pages.py
Adding page numbers and fixing running header and footer content for CFS pdfs
Page counts and the reference sit at the top of all pages
Bottom of the page has the running footer. Page breaks does not cause text to superimpose
=> ICMSLST-2734 Fixing page breaks and adding page numbers for CFS pdfs

Makefile, pii-ner-exclude.txt, requirements-base.txt, web/domains/template/context.py, web/domains/template/models.py, web/domains/user/views.py, web/mail/messages.py, web/mail/url_helpers.py, web/management/commands/update_email_data.py, web/management/commands/utils/add_template_data.py, web/templates/web/domains/template/detail.html, web/tests/domains/case/_import/sanctions/test_views.py, web/tests/domains/case/access/test_views.py, web/tests/domains/case/views/test_views_update_request.py, web/tests/mail/test_emails.py
PR includes
- Command to update all GovNotify template ids
- Command to update DB email copy
- Command to archive DB email templates that will no longer be used
- Update GovNotify lib to latest
- Fix to User activate / deactivate emails where email subject using incorrect field
- Added template vars to `AccessRequestClosedEmail` to support optional copy
- Fixed incorrect urls in `ApplicationUpdateResponseEmail`
To test
- Set the GOV NOTIFY settings to live
- Run `python manage.py update_email_data`
- Send emails and make sure they are using the new templates
- Run through a process of sending a DB email and check copy has been updated
- Log in to GOV Notify and view all new templates (in V2 dir)
=> ICMSLST-2700 - Email content update

config/env.py
Updated **ICMS_DJANGO_SESSION_COOKIE_AGE** ParamStore values in hotfix and prod to 3600 (1h)
=> ICMSLST-2757 Set default django cookie age to one hour.

web/static/web/css/pdfs/com-certificate-style.css, web/static/web/css/pdfs/constants.css, web/templates/pdf/export/com-certificate.html, web/utils/pdf/generator.py, web/utils/pdf/pages.py
Page breaks fixed by creating a first page with just a footer and merging it with the rest of the pages containing a larger bottom margin.
=> ICMSLST-2744 Fix COM Certificate styling on page breaks

pii-ner-exclude.txt, web/domains/user/forms.py, web/domains/user/models.py, web/domains/user/urls.py, web/domains/user/views.py, web/middleware/one_login.py, web/one_login/backends.py, web/one_login/constants.py, web/templates/web/domains/user/one_login/user_edit.html, web/tests/domains/user/test_forms.py, web/tests/domains/user/test_views.py, web/tests/middleware/test_one_login.py
Changes:
- Add NewUserUpdateView view.
- Update UserFullyRegisteredMiddleware to redirect to new view.
- Remove "one_login_unset" from User.full_name property.
- Move ONE_LOGIN_UNSET_NAME to constants.py file.
New view:
=> ICMSLST-2770 Add view to set new user details when first visiting site.

data_migration/queries/export_application/cfs.py
IS_EU_MARKET became the field for IS_UK_MARKET after the UK left the EU, but the value in the db remained unchanged
=> ICMSLST-2722 Data Migration - Fix CFS Schedule uk_market and export_only fields

data_migration/queries/import_application/fa/emails.py, pii-ner-exclude.txt
Changing the query as the previous caused multiple joins to the same row if an application had multiple constabulary emails
=> Data Migration - Fix constabulary emails query

web/domains/exporter/forms.py, web/domains/exporter/views.py, web/domains/importer/forms.py, web/templates/partial/importer/detail.html, web/templates/web/domains/exporter/detail.html, web/tests/domains/exporter/test_views.py
Changes:
- Make Registered Number optional when creating a main Importer.
- Make Registered Number optional when creating an agent Importer.
- Make Registered Number optional when creating a main Exporter.
- Fix exporter redirects to use correct query param name.
=> ICMSLST-2785 Make registered_number optional for all orgs and agents.

web/templates/registration/v1_account_recovery.html, web/templates/web/domains/user/user_edit.html
Rename "Account Recovery" to "Link your existing account".
Menu item label:
Account Recovery content changes:
=> ICMSLST-2797 Update Account Recovery page content.

web/static/web/css/pdfs/cfs-certificate-style.css, web/static/web/css/pdfs/com-certificate-style.css, web/static/web/css/pdfs/gmp-certificate-style.css
**COM Certificate**
Before
After
**GMP Certificate**
Before
After
**CFS Certificate**
Before
After
=> ICMSLST-2843 Fix overflow styling for GMP, CFS and COM certificate PDFs

pii-ner-exclude.txt, web/domains/case/_import/models.py, web/domains/case/utils.py, web/domains/chief/urls.py, web/domains/chief/views.py, web/templates/web/domains/chief/failed_licences.html, web/tests/domains/chief/test_views.py
Add the ability to recover from ICMS-HMRC serialization errors using the front end.
=> ICMSLST-2901 Add view to review a case with errors back to processing.

pii-ner-exclude.txt, web/domains/case/views/views_misc.py, web/tests/domains/case/views/test_views_misc.py
=> ICMSLST-2876 - FA-DFL -> Authorise Documents -> Response Documents -> Incorrect labels

.circleci/config.yml, .coveragerc
Removing web/utils/pdf/pages.py from coverage as those functions are implicitly tested through the PDF visual regression tests
=> Removing pdf/pages.py from coverage

pii-ner-exclude.txt, web/domains/case/forms.py, web/domains/case/views/views_misc.py, web/templates/forms/forms.html, web/templates/partial/case/export/sidebar-management.html, web/templates/partial/case/import/sidebar-management.html, web/templates/partial/withdrawal/box.html, web/templates/web/domains/case/withdraw.html
Changes:
- Update several places WithdrawApplication.Statuses is used.
- Add a missing form label
- Refactor how app withdrawals are shown.
You can no longer add multiple open withdrawal requests and can withdraw if needed:
=> ICMSLST-2830 Fix app withdrawal bugs relating to status refactor.

web/management/commands/add_dummy_data.py, web/management/commands/add_test_data.py
Fix warnings shown when running tests:
=> Fix naive datetime instances used for date_joined values.

web/domains/chief/urls.py, web/domains/chief/views.py, web/management/commands/check_icms_hmrc_connection.py
Changes:
- Add endpoint that ICMS-HMRC uses to test it can communicate with ICMS.
- Add management command to test ICMS can commumicate with ICMS-HMRC.
=> ICMSLST-2963 Add ability to test icms / icms-hmrc connections.

web/domains/section5/filters.py
=> ICMSLST-2948 Update Section 5 Clauses form to use a CheckboxInput.

pii-ner-exclude.txt, web/domains/case/access/views.py, web/templates/web/domains/case/access/close-access-request.html, web/templates/web/domains/case/access/management.html, web/tests/domains/case/access/test_views.py
When there is an open approval request prevent closure / re-linking of the access request.
=> ICMSLST-2853 Prevent linking / closure of access requests.

pii-ner-exclude.txt, web/templates/partial/case/case-note-box.html, web/templates/web/domains/case/manage/edit-note.html
Before (note an hour behind my local time on my mac - UTC):
After (correctly displays BST datetime):
=> Fix datetime formatting on case notes view.

pii-ner-exclude.txt, web/domains/exporter/models.py, web/domains/importer/models.py, web/templates/web/domains/case/export/partials/process.html, web/templates/web/domains/case/import/partials/process.html, web/templates/web/domains/case/view_case.html, web/templates/web/domains/workbasket/workbasket.html, web/tests/domains/case/_import/derogations/test_views.py, web/tests/domains/case/_import/sanctions/test_views.py
Import Application showing agent data:
Export Application showing agent data:
I kept the `Agent -` prefix in the workbasket after removing it from the model `__str__` methods:
=> ICMSLST-2941 Display agent info when viewing case.

web/domains/checker/views.py, web/tests/domains/checker/test_views.py, web/urls.py
Also remove require_exporter from CheckCertificateView as we are unsure what domain the V1 DNS will point.
=> Add extra path to point to V1ToV2ServiceRenameView view.

pii-ner-exclude.txt, web/domains/case/_import/fa_sil/views.py, web/templates/web/domains/case/import/fa-sil/view-verified-section5.html, web/templates/web/domains/case/import/partials/fa-sil/verified-section5-authorities.html
Changes:
- Update Show Details link to always show.
- Refactor details page UI.
- Fix permission checking when viewing details.
When viewing a case before:
When viewing a case after:
Updated view details view:
=> ICMSLST-2980 Always show Show Details link for section 5 authorities.

web/domains/case/export/utils.py, web/templates/web/domains/case/export/partials/cfs/schedule-products.html, web/tests/domains/case/export/test_utils.py
Made the spreadsheet uploaded less strict
- Doesn't require a sheet name. Will just take the first sheet if there are no sheets named "CFS Products"
- Will skip blank rows rather than raising a validation error
- As long as the first column is "Product Name" for non biocide, it will upload the first column of data regardless of whats in the other columns
Added a message to the screen to use the .xlsx template provided
=> ICMSLST-3005 CFS Spreadsheet Upload less strict for non biocide products

web/domains/case/access/forms.py, web/domains/case/access/urls.py, web/domains/case/access/views.py, web/templates/web/domains/case/access/close-access-request.html, web/templates/web/domains/case/access/management.html, web/tests/domains/case/access/test_views.py
Manage Access Request page with importer and agent foms:
Close access request message when agent hasn't been linked:
Manage Access Request page with complete approval showing agent can still be set after approval:
=> ICMSLST-2986 Add endpoint to link agents to access requests.

web/domains/workbasket/app_data.py, web/tests/domains/workbasket/test_views.py
Sanctions case officers will now see importer access requests in their workbasket:
=> ICMSLST-3010 Add importer access requests to Sanctions CO workbasket.

web/domains/case/access/forms.py, web/domains/case/access/views.py, web/templates/web/domains/case/access/close-access-request.html, web/tests/domains/case/access/test_views.py
If approving an access request then the org / agent must be set. If refusing an access request then both org and agent are optional.
Form error handling:
=> ICMSLST-3013 Update close access request logic.

web/domains/case/export/views.py
As long as the edit form is valid and the correct field is set the file upload links will show.
There is already logic in place to mark files as inactive if `application.gmp_certificate_issued` changes.
=> ICMSLST-2841 Fix logic used to show file upload forms.

web/domains/case/_import/fa_dfl/forms.py, web/domains/case/_import/fa_dfl/views.py, web/domains/case/_import/fa_sil/forms.py, web/domains/case/_import/sanctions/forms.py, web/tests/domains/case/_import/fa_dfl/test_forms.py, web/tests/domains/case/_import/fa_sil/test_forms.py, web/tests/domains/case/_import/sanctions/test_forms.py
Replace all whitespace characters in freetext import goods descriptions with a blank space. The whitespace characters are not visible in the frontend and cause issues when sent to icms-hmrc
Added tests for the import application forms that clean the whitespace characters
=> ECIL-217 Clean whitespace in goods descriptions for import applications

config/settings.py, pii-ner-exclude.txt
Using a separate cache for select2 to avoid conflicts with other caches, this is the recommended approach:
[https://github.com/applegrew/django-select2/blob/4e3bdc89185a45e319d54d16ed0b36f74674d58d/django_select2/cache.py#L10 ](https://github.com/applegrew/django-select2/blob/4e3bdc89185a45e319d54d16ed0b36f74674d58d/django_select2/cache.py#L10 )
=> ECIL-209 - Access Request - Link to Exporter Typeahead search not working

web/domains/case/access/views.py, web/domains/contacts/views.py, web/domains/importer/views.py, web/domains/user/views.py
A contact can be added to an organisation by the following methods:
1. Directly by an organisation admin in the edit org screen.
2. When an access request is approved.
3. When a user is invited to an organisation by another org contact.
4. When an individual importer is initially created.
=> ECIL-275 Add manage permission when a contact is added to an org.

.circleci/config.yml, .env.circleci, .env.local-docker, Makefile, README.md, config/cf_env.py, config/env.py, config/settings.py, config/settings_test.py, config/urls.py, docker-compose.yml, local_deployment/entry.sh, pii-ner-exclude.txt, web/end_to_end/conftest.py, web/end_to_end/test_utils.py, web/menu/menu.py, web/tests/domains/case/views/test_views_search.py, web/tests/test_urls.py, web/urls.py
Run two versions of ICMS to better reflect the future production infrastructure.
Added so that our end to end tests will run on different servers and test the dynamic urls.
=> ECIL-285 Add web-internal to local docker-compose.yml.

config/settings.py, pii-ner-exclude.txt, requirements-dev.txt, requirements-prod.txt, requirements/requirements-base.in, web/domains/case/models.py, web/domains/firearms/forms.py, web/ecil/forms.py, web/ecil/gds/forms/__init__.py, web/ecil/gds/forms/fields.py, web/ecil/gds/forms/forms.py, web/ecil/gds/forms/renderers.py, web/ecil/gds/forms/validators.py, web/ecil/urls.py, web/ecil/views.py, web/jinja2.py, web/menu/menu.py, web/migrations/0001_initial.py, web/templates/ecil/base.html, web/templates/ecil/gds/forms/div.html, web/templates/ecil/gds/forms/field.html, web/templates/ecil/gds_form.html, web/tests/ecil/gds/forms/test_fields.py, web/tests/ecil/test_views.py, web/urls.py
Changes:
- Upgrade django to 5.1
- Add gds character count field component.
- Add gds checkboxes field component.
- Add gds date field component.
- Add gds file field component.
- Add gds password field component.
- Add gds radio input field component.
- Add gds select field component.
- Add gds textarea field component.
- Add gds text input field component.
- Add custom GDSTemplateSetting form renderer.
- Add form template to render error summary.
- Add field template to render all gds form component macros.
- Add tests for all gds django form fields.
- Add example view using new form fields. 
**Example form:**
**Example form showing errors and error summary:**
=> ECIL-297 Add form fields for all GDS form components.   

web/auth/utils.py
This is an edge case for the following:
- User is a V1 user.
- User has an UserEmail record that they log in with where is_primary is set to False.
=> ECIL-201 Set is_verified for ICMS V1 users who haven't logged in yet.

config/settings.py, pii-ner-exclude.txt, web/misc/context_processors.py, web/templates/base.html, web/tests/misc/test_context_processors.py, web/tests/views/test_views.py
Turns the header a different colour on lower environments depending on site.
Caseworker:
Exporter:
Importer:
=> ECIL-421 - Change colour of banner for lower environments

pii-ner-exclude.txt, web/domains/case/access/views.py, web/domains/case/app_checks.py, web/templates/web/domains/case/access/close-access-request.html, web/tests/domains/case/access/test_views.py
Message shown to ILB if they try to close an AR with open FIRs
Post example after another fir is created (edge case)
=> ECIL-343 Prevent access requests being closed with open FIRs.

web/templates/base.html, web/templates/web/cookie-consent.html
Before:
After:
Also deleted redundant cookie consent content as we don't store GA cookies on the user's computer, this is done on GA via the value of the `accepted_ga_cookies` cookie
=> ECIL-340 - As a user, I need to be able to review my cookie acceptance

pii-ner-exclude.txt, web/domains/case/access/views.py, web/templates/web/domains/case/access/close-access-request.html, web/tests/domains/case/access/test_views.py
**Example access request with several FIRs (open and draft):**
**Message shown on Close Access Request view:**
**When viewing historical access request (everything apart from draft FIR is shown):**
=> ECIL-520 Update close access request view to close open FIRs.

web/domains/exporter/views.py, web/templates/web/domains/exporter/detail.html, web/templates/web/domains/exporter/edit.html, web/tests/domains/exporter/test_views.py
=> ECIL-491 - Remove back link to “Exporters” within the top task bar on caseworker

web/ecil/forms/forms_access_requests.py, web/ecil/forms/forms_new_user.py, web/ecil/views/views_access_requests.py, web/templates/ecil/access_request/exporter_countries-step.html
Changes:
- Limit list of export countries to 40.
- Change ExporterAccessRequestExportCountriesForm export_countries label and required error message.
- Add OneLoginNewUserUpdateForm first_name & last_name required error message.
- Add ExporterTriageForm applications required error message.
- Add Fake Continue button when no export countries are chosen to trigger correct error message.
=> ECIL-587 Add missing ECIL form validation and error messages.

web/domains/chief/client.py, web/domains/chief/serializers.py, web/domains/chief/types.py, web/static/web/css/pdfs/import/nuclear-material-licence-style.css, web/templates/pdf/import/nuclear-material-licence.html, web/tests/conftest.py, web/tests/domains/chief/test_serializers.py, web/utils/pdf/generator.py, web/utils/pdf/pages.py, web/utils/pdf/utils.py
Changes:
- ECIL-651 Send NMIL data to ICMS-HMRC.
- ECIL-666 Add placeholder NCIL licence generation code.
Example licenceData send to ICMS-HMRC:
```
1\fileHeader\ILBDOTI\CHIEF\licenceData\202503141517\3\N
2\licence\IMA/2025/00003\insert\GBSIL0000003D\SIL\I\20250314\20260331
3\trader\\GB123456789012341\\\Dummy importer 1\1 Whitehall Pl\Westminster\London\\\SW1A1HP
4\country\AF\\O
5\restrictions\The licence is only valid if you also hold authority of the Secretary of State for Defence under the Landmines Act 1988 to possess and meet the conditions set out in that authority. You have a responsibility to comply with any legislation relating to explosives, if relevant, and that this import licence does not replace this responsibility. Please contact the Health and Safety Executive for further …
```
=> ECIL-651 Send NMIL data to ICMS-HMRC.

pii-ner-exclude.txt, web/ecil/forms/forms_cfs.py, web/ecil/urls/urls_cfs.py, web/ecil/views/views_cfs.py, web/templates/ecil/cfs/help_text/schedule_statements_accordance_with_standards.html, web/templates/ecil/cfs/help_text/schedule_statements_is_responsible_person.html, web/tests/ecil/views/test_views_cfs.py
Changes:
- Add CFSScheduleStatementIsResponsiblePersonUpdateView.
- GB:      
- NI:      
- Add Add CFSScheduleStatementAccordanceWithStandardsUpdateView.
=> ECIL-713 Add CFS Schedule statement fields.

assets/css/uktrade-list-with-actions.css, pii-ner-exclude.txt, web/ecil/forms/forms_cfs.py, web/ecil/gds/component_serializers/list_with_actions.py, web/ecil/urls/urls_cfs.py, web/ecil/views/views_cfs.py, web/templates/ecil/cfs/help_text/schedule_raw_material_product_end_use.html, web/templates/ecil/cfs/schedule_product_add_another.html, web/templates/gds/components/list-with-actions/macro.html, web/tests/ecil/views/test_views_cfs.py
Changes:
- ECIL-742 Add CFSScheduleProductEndUseUpdateView view.
- ECIL-755 Add CFSScheduleProductUpdateView view.
- ECIL-744 Add CFSScheduleProductAddAnotherFormView view  
- ECIL-744 Add CFSScheduleProductConfirmRemoveFormView view
=> ECIL-740 Add several views relating to managing CFS schedule products.
